coverage:
  status:
    project:
      default:
        target: auto
        threshold: 1%
    patch:
      default:
        target: 80%
        threshold: 1%

flags:
  rust:
    carryforward: true
  flutter:
    carryforward: true
