// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'bridge.freezed.dart';

// These functions are ignored because they are not marked as `pub`: `config_to_engine`, `detect_monitors`, `is_direct_image`, `lock`, `message`, `monitor_from_engine`, `parse_hdr_mode`, `parse_hwdec`, `parse_layout`, `parse_tone_mapping_algorithm`, `preview_cache_path`, `wallpaper_to_dto`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `ServiceInner`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `from`

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<WayvidService>>
abstract class WayvidService implements RustOpaqueInterface {
  Future<void> applyWallpaper({required String path, String? output});

  Future<void> clearWallpaper({String? output});

  Future<void> createEngine({required EngineConfigDto config});

  Future<ServiceInfo> initialize();

  Future<PreviewDto> loadPreview({
    required String wallpaperId,
    required String path,
    required String wallpaperType,
    required int width,
    required int height,
  });

  // HINT: Make it `#[frb(sync)]` to let it become the default constructor of Dart class.
  static Future<WayvidService> newInstance() =>
      RustLib.instance.api.crateBridgeWayvidServiceNew();

  Future<void> openUrl({required String url});

  Future<void> pause({String? output});

  Future<List<ServiceEvent>> pollEvents();

  Future<List<MonitorDto>> refreshMonitors();

  Future<void> resume({String? output});

  Future<List<WallpaperDto>> scanFolder({required String path});

  Future<List<WallpaperDto>> scanWorkshop();

  Future<void> shutdown();

  Future<void> stopEngine();

  Future<void> updateEngineConfig({required EngineConfigDto config});
}

class BridgeError implements FrbException {
  final String code;
  final String message;

  const BridgeError({required this.code, required this.message});

  @override
  int get hashCode => code.hashCode ^ message.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BridgeError &&
          runtimeType == other.runtimeType &&
          code == other.code &&
          message == other.message;
}

class EngineConfigDto {
  final double volume;
  final int? fpsLimit;
  final bool loopPlayback;
  final String layout;
  final String hwdec;
  final bool mute;
  final double startTime;
  final double playbackRate;
  final String hdrMode;
  final String toneMappingAlgorithm;
  final double toneMappingParam;
  final String toneMappingMode;
  final bool toneMappingComputePeak;
  final bool autoPlay;
  final bool pauseOnBattery;

  const EngineConfigDto({
    required this.volume,
    this.fpsLimit,
    required this.loopPlayback,
    required this.layout,
    required this.hwdec,
    required this.mute,
    required this.startTime,
    required this.playbackRate,
    required this.hdrMode,
    required this.toneMappingAlgorithm,
    required this.toneMappingParam,
    required this.toneMappingMode,
    required this.toneMappingComputePeak,
    required this.autoPlay,
    required this.pauseOnBattery,
  });

  @override
  int get hashCode =>
      volume.hashCode ^
      fpsLimit.hashCode ^
      loopPlayback.hashCode ^
      layout.hashCode ^
      hwdec.hashCode ^
      mute.hashCode ^
      startTime.hashCode ^
      playbackRate.hashCode ^
      hdrMode.hashCode ^
      toneMappingAlgorithm.hashCode ^
      toneMappingParam.hashCode ^
      toneMappingMode.hashCode ^
      toneMappingComputePeak.hashCode ^
      autoPlay.hashCode ^
      pauseOnBattery.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is EngineConfigDto &&
          runtimeType == other.runtimeType &&
          volume == other.volume &&
          fpsLimit == other.fpsLimit &&
          loopPlayback == other.loopPlayback &&
          layout == other.layout &&
          hwdec == other.hwdec &&
          mute == other.mute &&
          startTime == other.startTime &&
          playbackRate == other.playbackRate &&
          hdrMode == other.hdrMode &&
          toneMappingAlgorithm == other.toneMappingAlgorithm &&
          toneMappingParam == other.toneMappingParam &&
          toneMappingMode == other.toneMappingMode &&
          toneMappingComputePeak == other.toneMappingComputePeak &&
          autoPlay == other.autoPlay &&
          pauseOnBattery == other.pauseOnBattery;
}

class MonitorDto {
  final String name;
  final int width;
  final int height;
  final int x;
  final int y;
  final double scale;
  final bool primary;
  final String? currentWallpaper;

  const MonitorDto({
    required this.name,
    required this.width,
    required this.height,
    required this.x,
    required this.y,
    required this.scale,
    required this.primary,
    this.currentWallpaper,
  });

  @override
  int get hashCode =>
      name.hashCode ^
      width.hashCode ^
      height.hashCode ^
      x.hashCode ^
      y.hashCode ^
      scale.hashCode ^
      primary.hashCode ^
      currentWallpaper.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is MonitorDto &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          width == other.width &&
          height == other.height &&
          x == other.x &&
          y == other.y &&
          scale == other.scale &&
          primary == other.primary &&
          currentWallpaper == other.currentWallpaper;
}

class PreviewDto {
  final String? imagePath;
  final Uint8List bytes;

  const PreviewDto({this.imagePath, required this.bytes});

  @override
  int get hashCode => imagePath.hashCode ^ bytes.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PreviewDto &&
          runtimeType == other.runtimeType &&
          imagePath == other.imagePath &&
          bytes == other.bytes;
}

@freezed
sealed class ServiceEvent with _$ServiceEvent {
  const ServiceEvent._();

  const factory ServiceEvent.engineStarted() = ServiceEvent_EngineStarted;
  const factory ServiceEvent.engineStopped() = ServiceEvent_EngineStopped;
  const factory ServiceEvent.wallpaperApplied({
    required String output,
    required String path,
  }) = ServiceEvent_WallpaperApplied;
  const factory ServiceEvent.wallpaperCleared({required String output}) =
      ServiceEvent_WallpaperCleared;
  const factory ServiceEvent.outputsChanged({
    required List<MonitorDto> outputs,
  }) = ServiceEvent_OutputsChanged;
  const factory ServiceEvent.error({
    required String code,
    required String message,
  }) = ServiceEvent_Error;
}

class ServiceInfo {
  final bool workshopAvailable;
  final bool engineRunning;

  const ServiceInfo({
    required this.workshopAvailable,
    required this.engineRunning,
  });

  @override
  int get hashCode => workshopAvailable.hashCode ^ engineRunning.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ServiceInfo &&
          runtimeType == other.runtimeType &&
          workshopAvailable == other.workshopAvailable &&
          engineRunning == other.engineRunning;
}

class WallpaperDto {
  final String id;
  final String name;
  final String sourcePath;
  final String? thumbnailPath;
  final String sourceType;
  final String wallpaperCategory;
  final String wallpaperType;
  final WallpaperMetadataDto metadata;
  final String addedAt;
  final String? lastUsed;

  const WallpaperDto({
    required this.id,
    required this.name,
    required this.sourcePath,
    this.thumbnailPath,
    required this.sourceType,
    required this.wallpaperCategory,
    required this.wallpaperType,
    required this.metadata,
    required this.addedAt,
    this.lastUsed,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      name.hashCode ^
      sourcePath.hashCode ^
      thumbnailPath.hashCode ^
      sourceType.hashCode ^
      wallpaperCategory.hashCode ^
      wallpaperType.hashCode ^
      metadata.hashCode ^
      addedAt.hashCode ^
      lastUsed.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is WallpaperDto &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          name == other.name &&
          sourcePath == other.sourcePath &&
          thumbnailPath == other.thumbnailPath &&
          sourceType == other.sourceType &&
          wallpaperCategory == other.wallpaperCategory &&
          wallpaperType == other.wallpaperType &&
          metadata == other.metadata &&
          addedAt == other.addedAt &&
          lastUsed == other.lastUsed;
}

class WallpaperMetadataDto {
  final String? title;
  final String? author;
  final String? description;
  final List<String> tags;
  final double? durationSecs;
  final int? resolutionWidth;
  final int? resolutionHeight;
  final BigInt? fileSize;
  final BigInt? workshopId;

  const WallpaperMetadataDto({
    this.title,
    this.author,
    this.description,
    required this.tags,
    this.durationSecs,
    this.resolutionWidth,
    this.resolutionHeight,
    this.fileSize,
    this.workshopId,
  });

  @override
  int get hashCode =>
      title.hashCode ^
      author.hashCode ^
      description.hashCode ^
      tags.hashCode ^
      durationSecs.hashCode ^
      resolutionWidth.hashCode ^
      resolutionHeight.hashCode ^
      fileSize.hashCode ^
      workshopId.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is WallpaperMetadataDto &&
          runtimeType == other.runtimeType &&
          title == other.title &&
          author == other.author &&
          description == other.description &&
          tags == other.tags &&
          durationSecs == other.durationSecs &&
          resolutionWidth == other.resolutionWidth &&
          resolutionHeight == other.resolutionHeight &&
          fileSize == other.fileSize &&
          workshopId == other.workshopId;
}
