// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'bridge.freezed.dart';

// These functions are ignored because they are not marked as `pub`: `apply_settings_patch`, `detect_monitors`, `lock`, `merge_wallpapers`, `message`, `save_wallpaper_state`, `settings_to_dto`, `source_type_name`, `thumbnail_cache_dir`, `thumbnail_cache_path`, `wallpaper_to_dto`, `wallpaper_type_name`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `ServiceInner`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `from`

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<WayvidService>>
abstract class WayvidService implements RustOpaqueInterface {
  Future<void> applyWallpaper({required String wallpaperId, String? output});

  Future<void> clearWallpaper({String? output});

  Future<SettingsDto> getSettings();

  Future<InitializationSnapshot> initialize();

  Future<List<WallpaperDto>> loadLibrary();

  Future<Uint8List> loadThumbnail({
    required String wallpaperId,
    required String path,
    required int width,
    required int height,
  });

  // HINT: Make it `#[frb(sync)]` to let it become the default constructor of Dart class.
  /// Construct the service without starting the playback engine.
  static Future<WayvidService> newInstance({required List<String> args}) =>
      RustLib.instance.api.crateBridgeWayvidServiceNew(args: args);

  Future<void> openUrl({required String url});

  Future<void> pause({String? output});

  Future<List<ServiceEvent>> pollEvents();

  Future<List<MonitorDto>> refreshMonitors();

  Future<void> resume({String? output});

  Future<List<WallpaperDto>> scanFolder({required String path});

  Future<List<WallpaperDto>> scanWorkshop();

  Future<void> shutdown();

  Future<void> startEngine();

  Future<void> stopEngine();

  Future<SettingsDto> updateSettings({required SettingsPatch patch});
}

/// Error returned by all public bridge operations.
class BridgeError implements FrbException {
  final String code;
  final String message;

  const BridgeError({required this.code, required this.message});

  @override
  int get hashCode => code.hashCode ^ message.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BridgeError &&
          runtimeType == other.runtimeType &&
          code == other.code &&
          message == other.message;
}

@freezed
sealed class FpsLimitPatch with _$FpsLimitPatch {
  const FpsLimitPatch._();

  const factory FpsLimitPatch.unlimited() = FpsLimitPatch_Unlimited;
  const factory FpsLimitPatch.value(int field0) = FpsLimitPatch_Value;
}

class GuiSettingsDto {
  final int windowWidth;
  final int windowHeight;
  final bool minimizeToTray;
  final bool startMinimized;
  final String theme;
  final String language;
  final String renderer;
  final bool sidebarCollapsed;
  final bool detailPanelVisible;

  const GuiSettingsDto({
    required this.windowWidth,
    required this.windowHeight,
    required this.minimizeToTray,
    required this.startMinimized,
    required this.theme,
    required this.language,
    required this.renderer,
    required this.sidebarCollapsed,
    required this.detailPanelVisible,
  });

  @override
  int get hashCode =>
      windowWidth.hashCode ^
      windowHeight.hashCode ^
      minimizeToTray.hashCode ^
      startMinimized.hashCode ^
      theme.hashCode ^
      language.hashCode ^
      renderer.hashCode ^
      sidebarCollapsed.hashCode ^
      detailPanelVisible.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is GuiSettingsDto &&
          runtimeType == other.runtimeType &&
          windowWidth == other.windowWidth &&
          windowHeight == other.windowHeight &&
          minimizeToTray == other.minimizeToTray &&
          startMinimized == other.startMinimized &&
          theme == other.theme &&
          language == other.language &&
          renderer == other.renderer &&
          sidebarCollapsed == other.sidebarCollapsed &&
          detailPanelVisible == other.detailPanelVisible;
}

class InitializationSnapshot {
  final SettingsDto settings;
  final bool workshopAvailable;
  final bool engineRunning;
  final bool trayAvailable;
  final bool anotherInstance;

  const InitializationSnapshot({
    required this.settings,
    required this.workshopAvailable,
    required this.engineRunning,
    required this.trayAvailable,
    required this.anotherInstance,
  });

  @override
  int get hashCode =>
      settings.hashCode ^
      workshopAvailable.hashCode ^
      engineRunning.hashCode ^
      trayAvailable.hashCode ^
      anotherInstance.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is InitializationSnapshot &&
          runtimeType == other.runtimeType &&
          settings == other.settings &&
          workshopAvailable == other.workshopAvailable &&
          engineRunning == other.engineRunning &&
          trayAvailable == other.trayAvailable &&
          anotherInstance == other.anotherInstance;
}

class MonitorDto {
  final String name;
  final int width;
  final int height;
  final int x;
  final int y;
  final double scale;
  final bool primary;
  final String? currentWallpaper;

  const MonitorDto({
    required this.name,
    required this.width,
    required this.height,
    required this.x,
    required this.y,
    required this.scale,
    required this.primary,
    this.currentWallpaper,
  });

  @override
  int get hashCode =>
      name.hashCode ^
      width.hashCode ^
      height.hashCode ^
      x.hashCode ^
      y.hashCode ^
      scale.hashCode ^
      primary.hashCode ^
      currentWallpaper.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is MonitorDto &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          width == other.width &&
          height == other.height &&
          x == other.x &&
          y == other.y &&
          scale == other.scale &&
          primary == other.primary &&
          currentWallpaper == other.currentWallpaper;
}

class PlaybackSettingsDto {
  final double volume;
  final int? fpsLimit;
  final String? preferredMonitor;
  final bool loopMode;
  final bool shuffle;

  const PlaybackSettingsDto({
    required this.volume,
    this.fpsLimit,
    this.preferredMonitor,
    required this.loopMode,
    required this.shuffle,
  });

  @override
  int get hashCode =>
      volume.hashCode ^
      fpsLimit.hashCode ^
      preferredMonitor.hashCode ^
      loopMode.hashCode ^
      shuffle.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PlaybackSettingsDto &&
          runtimeType == other.runtimeType &&
          volume == other.volume &&
          fpsLimit == other.fpsLimit &&
          preferredMonitor == other.preferredMonitor &&
          loopMode == other.loopMode &&
          shuffle == other.shuffle;
}

class PowerSettingsDto {
  final bool pauseOnBattery;
  final bool pauseOnFullscreen;
  final int? batteryFpsLimit;

  const PowerSettingsDto({
    required this.pauseOnBattery,
    required this.pauseOnFullscreen,
    this.batteryFpsLimit,
  });

  @override
  int get hashCode =>
      pauseOnBattery.hashCode ^
      pauseOnFullscreen.hashCode ^
      batteryFpsLimit.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PowerSettingsDto &&
          runtimeType == other.runtimeType &&
          pauseOnBattery == other.pauseOnBattery &&
          pauseOnFullscreen == other.pauseOnFullscreen &&
          batteryFpsLimit == other.batteryFpsLimit;
}

@freezed
sealed class ServiceEvent with _$ServiceEvent {
  const ServiceEvent._();

  const factory ServiceEvent.engineStarted() = ServiceEvent_EngineStarted;
  const factory ServiceEvent.engineStopped() = ServiceEvent_EngineStopped;
  const factory ServiceEvent.wallpaperApplied({
    required String output,
    required String path,
  }) = ServiceEvent_WallpaperApplied;
  const factory ServiceEvent.wallpaperCleared({required String output}) =
      ServiceEvent_WallpaperCleared;
  const factory ServiceEvent.outputsChanged({
    required List<MonitorDto> outputs,
  }) = ServiceEvent_OutputsChanged;
  const factory ServiceEvent.showWindow() = ServiceEvent_ShowWindow;
  const factory ServiceEvent.trayAction({required String action}) =
      ServiceEvent_TrayAction;
  const factory ServiceEvent.error({
    required String code,
    required String message,
  }) = ServiceEvent_Error;
}

class SettingsDto {
  final GuiSettingsDto gui;
  final PlaybackSettingsDto playback;
  final bool autostartEnabled;
  final bool restoreLastWallpaper;
  final PowerSettingsDto power;
  final List<String> libraryFolders;

  const SettingsDto({
    required this.gui,
    required this.playback,
    required this.autostartEnabled,
    required this.restoreLastWallpaper,
    required this.power,
    required this.libraryFolders,
  });

  @override
  int get hashCode =>
      gui.hashCode ^
      playback.hashCode ^
      autostartEnabled.hashCode ^
      restoreLastWallpaper.hashCode ^
      power.hashCode ^
      libraryFolders.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SettingsDto &&
          runtimeType == other.runtimeType &&
          gui == other.gui &&
          playback == other.playback &&
          autostartEnabled == other.autostartEnabled &&
          restoreLastWallpaper == other.restoreLastWallpaper &&
          power == other.power &&
          libraryFolders == other.libraryFolders;
}

class SettingsPatch {
  final int? windowWidth;
  final int? windowHeight;
  final bool? minimizeToTray;
  final bool? startMinimized;
  final String? theme;
  final String? language;
  final String? renderer;
  final bool? sidebarCollapsed;
  final bool? detailPanelVisible;
  final double? volume;
  final FpsLimitPatch? fpsLimit;
  final bool? pauseOnBattery;
  final bool? pauseOnFullscreen;
  final bool? autostartEnabled;
  final bool? restoreLastWallpaper;
  final List<String>? libraryFolders;

  const SettingsPatch({
    this.windowWidth,
    this.windowHeight,
    this.minimizeToTray,
    this.startMinimized,
    this.theme,
    this.language,
    this.renderer,
    this.sidebarCollapsed,
    this.detailPanelVisible,
    this.volume,
    this.fpsLimit,
    this.pauseOnBattery,
    this.pauseOnFullscreen,
    this.autostartEnabled,
    this.restoreLastWallpaper,
    this.libraryFolders,
  });

  static Future<SettingsPatch> default_() =>
      RustLib.instance.api.crateBridgeSettingsPatchDefault();

  @override
  int get hashCode =>
      windowWidth.hashCode ^
      windowHeight.hashCode ^
      minimizeToTray.hashCode ^
      startMinimized.hashCode ^
      theme.hashCode ^
      language.hashCode ^
      renderer.hashCode ^
      sidebarCollapsed.hashCode ^
      detailPanelVisible.hashCode ^
      volume.hashCode ^
      fpsLimit.hashCode ^
      pauseOnBattery.hashCode ^
      pauseOnFullscreen.hashCode ^
      autostartEnabled.hashCode ^
      restoreLastWallpaper.hashCode ^
      libraryFolders.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SettingsPatch &&
          runtimeType == other.runtimeType &&
          windowWidth == other.windowWidth &&
          windowHeight == other.windowHeight &&
          minimizeToTray == other.minimizeToTray &&
          startMinimized == other.startMinimized &&
          theme == other.theme &&
          language == other.language &&
          renderer == other.renderer &&
          sidebarCollapsed == other.sidebarCollapsed &&
          detailPanelVisible == other.detailPanelVisible &&
          volume == other.volume &&
          fpsLimit == other.fpsLimit &&
          pauseOnBattery == other.pauseOnBattery &&
          pauseOnFullscreen == other.pauseOnFullscreen &&
          autostartEnabled == other.autostartEnabled &&
          restoreLastWallpaper == other.restoreLastWallpaper &&
          libraryFolders == other.libraryFolders;
}

class WallpaperDto {
  final String id;
  final String name;
  final String sourcePath;
  final String? thumbnailPath;
  final String sourceType;
  final String wallpaperType;
  final WallpaperMetadataDto metadata;
  final String addedAt;
  final String? lastUsed;

  const WallpaperDto({
    required this.id,
    required this.name,
    required this.sourcePath,
    this.thumbnailPath,
    required this.sourceType,
    required this.wallpaperType,
    required this.metadata,
    required this.addedAt,
    this.lastUsed,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      name.hashCode ^
      sourcePath.hashCode ^
      thumbnailPath.hashCode ^
      sourceType.hashCode ^
      wallpaperType.hashCode ^
      metadata.hashCode ^
      addedAt.hashCode ^
      lastUsed.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is WallpaperDto &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          name == other.name &&
          sourcePath == other.sourcePath &&
          thumbnailPath == other.thumbnailPath &&
          sourceType == other.sourceType &&
          wallpaperType == other.wallpaperType &&
          metadata == other.metadata &&
          addedAt == other.addedAt &&
          lastUsed == other.lastUsed;
}

class WallpaperMetadataDto {
  final String? title;
  final String? author;
  final String? description;
  final List<String> tags;
  final double? durationSecs;
  final int? resolutionWidth;
  final int? resolutionHeight;
  final BigInt? fileSize;
  final BigInt? workshopId;

  const WallpaperMetadataDto({
    this.title,
    this.author,
    this.description,
    required this.tags,
    this.durationSecs,
    this.resolutionWidth,
    this.resolutionHeight,
    this.fileSize,
    this.workshopId,
  });

  @override
  int get hashCode =>
      title.hashCode ^
      author.hashCode ^
      description.hashCode ^
      tags.hashCode ^
      durationSecs.hashCode ^
      resolutionWidth.hashCode ^
      resolutionHeight.hashCode ^
      fileSize.hashCode ^
      workshopId.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is WallpaperMetadataDto &&
          runtimeType == other.runtimeType &&
          title == other.title &&
          author == other.author &&
          description == other.description &&
          tags == other.tags &&
          durationSecs == other.durationSecs &&
          resolutionWidth == other.resolutionWidth &&
          resolutionHeight == other.resolutionHeight &&
          fileSize == other.fileSize &&
          workshopId == other.workshopId;
}
