// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'bridge.dart';

import 'dart:async';
import 'dart:convert';

import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Main entrypoint of the Rust API
class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
  @internal
  static final instance = RustLib._();

  RustLib._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    RustLibApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({required RustLibApi api}) {
    instance.initMockImpl(api: api);
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor =>
      RustLibApiImpl.new;

  @override
  WireConstructor<RustLibWire> get wireConstructor =>
      RustLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {}

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.12.0';

  @override
  int get rustContentHash => -1913217904;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
        stem: 'wayvid_gui',
        ioDirectory: 'rust/target/release/',
        webPrefix: 'pkg/',
        wasmBindgenName: 'wasm_bindgen',
      );
}

abstract class RustLibApi extends BaseApi {
  Future<void> crateBridgeWayvidServiceApplyWallpaper({
    required WayvidService that,
    required String path,
    String? output,
  });

  Future<void> crateBridgeWayvidServiceClearWallpaper({
    required WayvidService that,
    String? output,
  });

  Future<void> crateBridgeWayvidServiceCreateEngine({
    required WayvidService that,
    required EngineConfigDto config,
  });

  Future<ServiceInfo> crateBridgeWayvidServiceInitialize({
    required WayvidService that,
  });

  Future<PreviewDto> crateBridgeWayvidServiceLoadPreview({
    required WayvidService that,
    required String wallpaperId,
    required String path,
    required String wallpaperType,
    required int width,
    required int height,
  });

  Future<WayvidService> crateBridgeWayvidServiceNew();

  Future<void> crateBridgeWayvidServiceOpenUrl({
    required WayvidService that,
    required String url,
  });

  Future<void> crateBridgeWayvidServicePause({
    required WayvidService that,
    String? output,
  });

  Future<List<ServiceEvent>> crateBridgeWayvidServicePollEvents({
    required WayvidService that,
  });

  Future<List<MonitorDto>> crateBridgeWayvidServiceRefreshMonitors({
    required WayvidService that,
  });

  Future<void> crateBridgeWayvidServiceResume({
    required WayvidService that,
    String? output,
  });

  Future<List<WallpaperDto>> crateBridgeWayvidServiceScanFolder({
    required WayvidService that,
    required String path,
  });

  Future<List<WallpaperDto>> crateBridgeWayvidServiceScanWorkshop({
    required WayvidService that,
  });

  Future<void> crateBridgeWayvidServiceShutdown({required WayvidService that});

  Future<void> crateBridgeWayvidServiceStopEngine({
    required WayvidService that,
  });

  Future<void> crateBridgeWayvidServiceUpdateEngineConfig({
    required WayvidService that,
    required EngineConfigDto config,
  });

  RustArcIncrementStrongCountFnType
  get rust_arc_increment_strong_count_WayvidService;

  RustArcDecrementStrongCountFnType
  get rust_arc_decrement_strong_count_WayvidService;

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_WayvidServicePtr;
}

class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
  RustLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  Future<void> crateBridgeWayvidServiceApplyWallpaper({
    required WayvidService that,
    required String path,
    String? output,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWayvidService(
            that,
            serializer,
          );
          sse_encode_String(path, serializer);
          sse_encode_opt_String(output, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 1,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_bridge_error,
        ),
        constMeta: kCrateBridgeWayvidServiceApplyWallpaperConstMeta,
        argValues: [that, path, output],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateBridgeWayvidServiceApplyWallpaperConstMeta =>
      const TaskConstMeta(
        debugName: "WayvidService_apply_wallpaper",
        argNames: ["that", "path", "output"],
      );

  @override
  Future<void> crateBridgeWayvidServiceClearWallpaper({
    required WayvidService that,
    String? output,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWayvidService(
            that,
            serializer,
          );
          sse_encode_opt_String(output, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 2,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_bridge_error,
        ),
        constMeta: kCrateBridgeWayvidServiceClearWallpaperConstMeta,
        argValues: [that, output],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateBridgeWayvidServiceClearWallpaperConstMeta =>
      const TaskConstMeta(
        debugName: "WayvidService_clear_wallpaper",
        argNames: ["that", "output"],
      );

  @override
  Future<void> crateBridgeWayvidServiceCreateEngine({
    required WayvidService that,
    required EngineConfigDto config,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWayvidService(
            that,
            serializer,
          );
          sse_encode_box_autoadd_engine_config_dto(config, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 3,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_bridge_error,
        ),
        constMeta: kCrateBridgeWayvidServiceCreateEngineConstMeta,
        argValues: [that, config],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateBridgeWayvidServiceCreateEngineConstMeta =>
      const TaskConstMeta(
        debugName: "WayvidService_create_engine",
        argNames: ["that", "config"],
      );

  @override
  Future<ServiceInfo> crateBridgeWayvidServiceInitialize({
    required WayvidService that,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWayvidService(
            that,
            serializer,
          );
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 4,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_service_info,
          decodeErrorData: sse_decode_bridge_error,
        ),
        constMeta: kCrateBridgeWayvidServiceInitializeConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateBridgeWayvidServiceInitializeConstMeta =>
      const TaskConstMeta(
        debugName: "WayvidService_initialize",
        argNames: ["that"],
      );

  @override
  Future<PreviewDto> crateBridgeWayvidServiceLoadPreview({
    required WayvidService that,
    required String wallpaperId,
    required String path,
    required String wallpaperType,
    required int width,
    required int height,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWayvidService(
            that,
            serializer,
          );
          sse_encode_String(wallpaperId, serializer);
          sse_encode_String(path, serializer);
          sse_encode_String(wallpaperType, serializer);
          sse_encode_u_32(width, serializer);
          sse_encode_u_32(height, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 5,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_preview_dto,
          decodeErrorData: sse_decode_bridge_error,
        ),
        constMeta: kCrateBridgeWayvidServiceLoadPreviewConstMeta,
        argValues: [that, wallpaperId, path, wallpaperType, width, height],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateBridgeWayvidServiceLoadPreviewConstMeta =>
      const TaskConstMeta(
        debugName: "WayvidService_load_preview",
        argNames: [
          "that",
          "wallpaperId",
          "path",
          "wallpaperType",
          "width",
          "height",
        ],
      );

  @override
  Future<WayvidService> crateBridgeWayvidServiceNew() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 6,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData:
              sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWayvidService,
          decodeErrorData: sse_decode_bridge_error,
        ),
        constMeta: kCrateBridgeWayvidServiceNewConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateBridgeWayvidServiceNewConstMeta =>
      const TaskConstMeta(debugName: "WayvidService_new", argNames: []);

  @override
  Future<void> crateBridgeWayvidServiceOpenUrl({
    required WayvidService that,
    required String url,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWayvidService(
            that,
            serializer,
          );
          sse_encode_String(url, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 7,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_bridge_error,
        ),
        constMeta: kCrateBridgeWayvidServiceOpenUrlConstMeta,
        argValues: [that, url],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateBridgeWayvidServiceOpenUrlConstMeta =>
      const TaskConstMeta(
        debugName: "WayvidService_open_url",
        argNames: ["that", "url"],
      );

  @override
  Future<void> crateBridgeWayvidServicePause({
    required WayvidService that,
    String? output,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWayvidService(
            that,
            serializer,
          );
          sse_encode_opt_String(output, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 8,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_bridge_error,
        ),
        constMeta: kCrateBridgeWayvidServicePauseConstMeta,
        argValues: [that, output],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateBridgeWayvidServicePauseConstMeta =>
      const TaskConstMeta(
        debugName: "WayvidService_pause",
        argNames: ["that", "output"],
      );

  @override
  Future<List<ServiceEvent>> crateBridgeWayvidServicePollEvents({
    required WayvidService that,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWayvidService(
            that,
            serializer,
          );
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 9,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_service_event,
          decodeErrorData: sse_decode_bridge_error,
        ),
        constMeta: kCrateBridgeWayvidServicePollEventsConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateBridgeWayvidServicePollEventsConstMeta =>
      const TaskConstMeta(
        debugName: "WayvidService_poll_events",
        argNames: ["that"],
      );

  @override
  Future<List<MonitorDto>> crateBridgeWayvidServiceRefreshMonitors({
    required WayvidService that,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWayvidService(
            that,
            serializer,
          );
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 10,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_monitor_dto,
          decodeErrorData: sse_decode_bridge_error,
        ),
        constMeta: kCrateBridgeWayvidServiceRefreshMonitorsConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateBridgeWayvidServiceRefreshMonitorsConstMeta =>
      const TaskConstMeta(
        debugName: "WayvidService_refresh_monitors",
        argNames: ["that"],
      );

  @override
  Future<void> crateBridgeWayvidServiceResume({
    required WayvidService that,
    String? output,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWayvidService(
            that,
            serializer,
          );
          sse_encode_opt_String(output, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 11,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_bridge_error,
        ),
        constMeta: kCrateBridgeWayvidServiceResumeConstMeta,
        argValues: [that, output],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateBridgeWayvidServiceResumeConstMeta =>
      const TaskConstMeta(
        debugName: "WayvidService_resume",
        argNames: ["that", "output"],
      );

  @override
  Future<List<WallpaperDto>> crateBridgeWayvidServiceScanFolder({
    required WayvidService that,
    required String path,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWayvidService(
            that,
            serializer,
          );
          sse_encode_String(path, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 12,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_wallpaper_dto,
          decodeErrorData: sse_decode_bridge_error,
        ),
        constMeta: kCrateBridgeWayvidServiceScanFolderConstMeta,
        argValues: [that, path],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateBridgeWayvidServiceScanFolderConstMeta =>
      const TaskConstMeta(
        debugName: "WayvidService_scan_folder",
        argNames: ["that", "path"],
      );

  @override
  Future<List<WallpaperDto>> crateBridgeWayvidServiceScanWorkshop({
    required WayvidService that,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWayvidService(
            that,
            serializer,
          );
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 13,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_wallpaper_dto,
          decodeErrorData: sse_decode_bridge_error,
        ),
        constMeta: kCrateBridgeWayvidServiceScanWorkshopConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateBridgeWayvidServiceScanWorkshopConstMeta =>
      const TaskConstMeta(
        debugName: "WayvidService_scan_workshop",
        argNames: ["that"],
      );

  @override
  Future<void> crateBridgeWayvidServiceShutdown({required WayvidService that}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWayvidService(
            that,
            serializer,
          );
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 14,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_bridge_error,
        ),
        constMeta: kCrateBridgeWayvidServiceShutdownConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateBridgeWayvidServiceShutdownConstMeta =>
      const TaskConstMeta(
        debugName: "WayvidService_shutdown",
        argNames: ["that"],
      );

  @override
  Future<void> crateBridgeWayvidServiceStopEngine({
    required WayvidService that,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWayvidService(
            that,
            serializer,
          );
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 15,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_bridge_error,
        ),
        constMeta: kCrateBridgeWayvidServiceStopEngineConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateBridgeWayvidServiceStopEngineConstMeta =>
      const TaskConstMeta(
        debugName: "WayvidService_stop_engine",
        argNames: ["that"],
      );

  @override
  Future<void> crateBridgeWayvidServiceUpdateEngineConfig({
    required WayvidService that,
    required EngineConfigDto config,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWayvidService(
            that,
            serializer,
          );
          sse_encode_box_autoadd_engine_config_dto(config, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 16,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_bridge_error,
        ),
        constMeta: kCrateBridgeWayvidServiceUpdateEngineConfigConstMeta,
        argValues: [that, config],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateBridgeWayvidServiceUpdateEngineConfigConstMeta =>
      const TaskConstMeta(
        debugName: "WayvidService_update_engine_config",
        argNames: ["that", "config"],
      );

  RustArcIncrementStrongCountFnType
  get rust_arc_increment_strong_count_WayvidService => wire
      .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWayvidService;

  RustArcDecrementStrongCountFnType
  get rust_arc_decrement_strong_count_WayvidService => wire
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWayvidService;

  @protected
  WayvidService
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWayvidService(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return WayvidServiceImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  WayvidService
  dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWayvidService(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return WayvidServiceImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  WayvidService
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWayvidService(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return WayvidServiceImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  bool dco_decode_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as bool;
  }

  @protected
  EngineConfigDto dco_decode_box_autoadd_engine_config_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_engine_config_dto(raw);
  }

  @protected
  double dco_decode_box_autoadd_f_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as double;
  }

  @protected
  int dco_decode_box_autoadd_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  BigInt dco_decode_box_autoadd_u_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_u_64(raw);
  }

  @protected
  BridgeError dco_decode_bridge_error(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return BridgeError(
      code: dco_decode_String(arr[0]),
      message: dco_decode_String(arr[1]),
    );
  }

  @protected
  EngineConfigDto dco_decode_engine_config_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 15)
      throw Exception('unexpected arr length: expect 15 but see ${arr.length}');
    return EngineConfigDto(
      volume: dco_decode_f_64(arr[0]),
      fpsLimit: dco_decode_opt_box_autoadd_u_32(arr[1]),
      loopPlayback: dco_decode_bool(arr[2]),
      layout: dco_decode_String(arr[3]),
      hwdec: dco_decode_String(arr[4]),
      mute: dco_decode_bool(arr[5]),
      startTime: dco_decode_f_64(arr[6]),
      playbackRate: dco_decode_f_64(arr[7]),
      hdrMode: dco_decode_String(arr[8]),
      toneMappingAlgorithm: dco_decode_String(arr[9]),
      toneMappingParam: dco_decode_f_64(arr[10]),
      toneMappingMode: dco_decode_String(arr[11]),
      toneMappingComputePeak: dco_decode_bool(arr[12]),
      autoPlay: dco_decode_bool(arr[13]),
      pauseOnBattery: dco_decode_bool(arr[14]),
    );
  }

  @protected
  double dco_decode_f_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as double;
  }

  @protected
  int dco_decode_i_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  List<String> dco_decode_list_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_String).toList();
  }

  @protected
  List<MonitorDto> dco_decode_list_monitor_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_monitor_dto).toList();
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  List<ServiceEvent> dco_decode_list_service_event(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_service_event).toList();
  }

  @protected
  List<WallpaperDto> dco_decode_list_wallpaper_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_wallpaper_dto).toList();
  }

  @protected
  MonitorDto dco_decode_monitor_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 8)
      throw Exception('unexpected arr length: expect 8 but see ${arr.length}');
    return MonitorDto(
      name: dco_decode_String(arr[0]),
      width: dco_decode_u_32(arr[1]),
      height: dco_decode_u_32(arr[2]),
      x: dco_decode_i_32(arr[3]),
      y: dco_decode_i_32(arr[4]),
      scale: dco_decode_f_64(arr[5]),
      primary: dco_decode_bool(arr[6]),
      currentWallpaper: dco_decode_opt_String(arr[7]),
    );
  }

  @protected
  String? dco_decode_opt_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_String(raw);
  }

  @protected
  double? dco_decode_opt_box_autoadd_f_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_f_64(raw);
  }

  @protected
  int? dco_decode_opt_box_autoadd_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_u_32(raw);
  }

  @protected
  BigInt? dco_decode_opt_box_autoadd_u_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_u_64(raw);
  }

  @protected
  PreviewDto dco_decode_preview_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return PreviewDto(
      imagePath: dco_decode_opt_String(arr[0]),
      bytes: dco_decode_list_prim_u_8_strict(arr[1]),
    );
  }

  @protected
  ServiceEvent dco_decode_service_event(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    switch (raw[0]) {
      case 0:
        return ServiceEvent_EngineStarted();
      case 1:
        return ServiceEvent_EngineStopped();
      case 2:
        return ServiceEvent_WallpaperApplied(
          output: dco_decode_String(raw[1]),
          path: dco_decode_String(raw[2]),
        );
      case 3:
        return ServiceEvent_WallpaperCleared(output: dco_decode_String(raw[1]));
      case 4:
        return ServiceEvent_OutputsChanged(
          outputs: dco_decode_list_monitor_dto(raw[1]),
        );
      case 5:
        return ServiceEvent_Error(
          code: dco_decode_String(raw[1]),
          message: dco_decode_String(raw[2]),
        );
      default:
        throw Exception("unreachable");
    }
  }

  @protected
  ServiceInfo dco_decode_service_info(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return ServiceInfo(
      workshopAvailable: dco_decode_bool(arr[0]),
      engineRunning: dco_decode_bool(arr[1]),
    );
  }

  @protected
  int dco_decode_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  BigInt dco_decode_u_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeU64(raw);
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  BigInt dco_decode_usize(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeU64(raw);
  }

  @protected
  WallpaperDto dco_decode_wallpaper_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 10)
      throw Exception('unexpected arr length: expect 10 but see ${arr.length}');
    return WallpaperDto(
      id: dco_decode_String(arr[0]),
      name: dco_decode_String(arr[1]),
      sourcePath: dco_decode_String(arr[2]),
      thumbnailPath: dco_decode_opt_String(arr[3]),
      sourceType: dco_decode_String(arr[4]),
      wallpaperCategory: dco_decode_String(arr[5]),
      wallpaperType: dco_decode_String(arr[6]),
      metadata: dco_decode_wallpaper_metadata_dto(arr[7]),
      addedAt: dco_decode_String(arr[8]),
      lastUsed: dco_decode_opt_String(arr[9]),
    );
  }

  @protected
  WallpaperMetadataDto dco_decode_wallpaper_metadata_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 9)
      throw Exception('unexpected arr length: expect 9 but see ${arr.length}');
    return WallpaperMetadataDto(
      title: dco_decode_opt_String(arr[0]),
      author: dco_decode_opt_String(arr[1]),
      description: dco_decode_opt_String(arr[2]),
      tags: dco_decode_list_String(arr[3]),
      durationSecs: dco_decode_opt_box_autoadd_f_64(arr[4]),
      resolutionWidth: dco_decode_opt_box_autoadd_u_32(arr[5]),
      resolutionHeight: dco_decode_opt_box_autoadd_u_32(arr[6]),
      fileSize: dco_decode_opt_box_autoadd_u_64(arr[7]),
      workshopId: dco_decode_opt_box_autoadd_u_64(arr[8]),
    );
  }

  @protected
  WayvidService
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWayvidService(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return WayvidServiceImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  WayvidService
  sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWayvidService(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return WayvidServiceImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  WayvidService
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWayvidService(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return WayvidServiceImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  EngineConfigDto sse_decode_box_autoadd_engine_config_dto(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_engine_config_dto(deserializer));
  }

  @protected
  double sse_decode_box_autoadd_f_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_f_64(deserializer));
  }

  @protected
  int sse_decode_box_autoadd_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_u_32(deserializer));
  }

  @protected
  BigInt sse_decode_box_autoadd_u_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_u_64(deserializer));
  }

  @protected
  BridgeError sse_decode_bridge_error(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_code = sse_decode_String(deserializer);
    var var_message = sse_decode_String(deserializer);
    return BridgeError(code: var_code, message: var_message);
  }

  @protected
  EngineConfigDto sse_decode_engine_config_dto(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_volume = sse_decode_f_64(deserializer);
    var var_fpsLimit = sse_decode_opt_box_autoadd_u_32(deserializer);
    var var_loopPlayback = sse_decode_bool(deserializer);
    var var_layout = sse_decode_String(deserializer);
    var var_hwdec = sse_decode_String(deserializer);
    var var_mute = sse_decode_bool(deserializer);
    var var_startTime = sse_decode_f_64(deserializer);
    var var_playbackRate = sse_decode_f_64(deserializer);
    var var_hdrMode = sse_decode_String(deserializer);
    var var_toneMappingAlgorithm = sse_decode_String(deserializer);
    var var_toneMappingParam = sse_decode_f_64(deserializer);
    var var_toneMappingMode = sse_decode_String(deserializer);
    var var_toneMappingComputePeak = sse_decode_bool(deserializer);
    var var_autoPlay = sse_decode_bool(deserializer);
    var var_pauseOnBattery = sse_decode_bool(deserializer);
    return EngineConfigDto(
      volume: var_volume,
      fpsLimit: var_fpsLimit,
      loopPlayback: var_loopPlayback,
      layout: var_layout,
      hwdec: var_hwdec,
      mute: var_mute,
      startTime: var_startTime,
      playbackRate: var_playbackRate,
      hdrMode: var_hdrMode,
      toneMappingAlgorithm: var_toneMappingAlgorithm,
      toneMappingParam: var_toneMappingParam,
      toneMappingMode: var_toneMappingMode,
      toneMappingComputePeak: var_toneMappingComputePeak,
      autoPlay: var_autoPlay,
      pauseOnBattery: var_pauseOnBattery,
    );
  }

  @protected
  double sse_decode_f_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getFloat64();
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <String>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_String(deserializer));
    }
    return ans_;
  }

  @protected
  List<MonitorDto> sse_decode_list_monitor_dto(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <MonitorDto>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_monitor_dto(deserializer));
    }
    return ans_;
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  List<ServiceEvent> sse_decode_list_service_event(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <ServiceEvent>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_service_event(deserializer));
    }
    return ans_;
  }

  @protected
  List<WallpaperDto> sse_decode_list_wallpaper_dto(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <WallpaperDto>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_wallpaper_dto(deserializer));
    }
    return ans_;
  }

  @protected
  MonitorDto sse_decode_monitor_dto(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_name = sse_decode_String(deserializer);
    var var_width = sse_decode_u_32(deserializer);
    var var_height = sse_decode_u_32(deserializer);
    var var_x = sse_decode_i_32(deserializer);
    var var_y = sse_decode_i_32(deserializer);
    var var_scale = sse_decode_f_64(deserializer);
    var var_primary = sse_decode_bool(deserializer);
    var var_currentWallpaper = sse_decode_opt_String(deserializer);
    return MonitorDto(
      name: var_name,
      width: var_width,
      height: var_height,
      x: var_x,
      y: var_y,
      scale: var_scale,
      primary: var_primary,
      currentWallpaper: var_currentWallpaper,
    );
  }

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_String(deserializer));
    } else {
      return null;
    }
  }

  @protected
  double? sse_decode_opt_box_autoadd_f_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_f_64(deserializer));
    } else {
      return null;
    }
  }

  @protected
  int? sse_decode_opt_box_autoadd_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_u_32(deserializer));
    } else {
      return null;
    }
  }

  @protected
  BigInt? sse_decode_opt_box_autoadd_u_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_u_64(deserializer));
    } else {
      return null;
    }
  }

  @protected
  PreviewDto sse_decode_preview_dto(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_imagePath = sse_decode_opt_String(deserializer);
    var var_bytes = sse_decode_list_prim_u_8_strict(deserializer);
    return PreviewDto(imagePath: var_imagePath, bytes: var_bytes);
  }

  @protected
  ServiceEvent sse_decode_service_event(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var tag_ = sse_decode_i_32(deserializer);
    switch (tag_) {
      case 0:
        return ServiceEvent_EngineStarted();
      case 1:
        return ServiceEvent_EngineStopped();
      case 2:
        var var_output = sse_decode_String(deserializer);
        var var_path = sse_decode_String(deserializer);
        return ServiceEvent_WallpaperApplied(
          output: var_output,
          path: var_path,
        );
      case 3:
        var var_output = sse_decode_String(deserializer);
        return ServiceEvent_WallpaperCleared(output: var_output);
      case 4:
        var var_outputs = sse_decode_list_monitor_dto(deserializer);
        return ServiceEvent_OutputsChanged(outputs: var_outputs);
      case 5:
        var var_code = sse_decode_String(deserializer);
        var var_message = sse_decode_String(deserializer);
        return ServiceEvent_Error(code: var_code, message: var_message);
      default:
        throw UnimplementedError('');
    }
  }

  @protected
  ServiceInfo sse_decode_service_info(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_workshopAvailable = sse_decode_bool(deserializer);
    var var_engineRunning = sse_decode_bool(deserializer);
    return ServiceInfo(
      workshopAvailable: var_workshopAvailable,
      engineRunning: var_engineRunning,
    );
  }

  @protected
  int sse_decode_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint32();
  }

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getBigUint64();
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  BigInt sse_decode_usize(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getBigUint64();
  }

  @protected
  WallpaperDto sse_decode_wallpaper_dto(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_id = sse_decode_String(deserializer);
    var var_name = sse_decode_String(deserializer);
    var var_sourcePath = sse_decode_String(deserializer);
    var var_thumbnailPath = sse_decode_opt_String(deserializer);
    var var_sourceType = sse_decode_String(deserializer);
    var var_wallpaperCategory = sse_decode_String(deserializer);
    var var_wallpaperType = sse_decode_String(deserializer);
    var var_metadata = sse_decode_wallpaper_metadata_dto(deserializer);
    var var_addedAt = sse_decode_String(deserializer);
    var var_lastUsed = sse_decode_opt_String(deserializer);
    return WallpaperDto(
      id: var_id,
      name: var_name,
      sourcePath: var_sourcePath,
      thumbnailPath: var_thumbnailPath,
      sourceType: var_sourceType,
      wallpaperCategory: var_wallpaperCategory,
      wallpaperType: var_wallpaperType,
      metadata: var_metadata,
      addedAt: var_addedAt,
      lastUsed: var_lastUsed,
    );
  }

  @protected
  WallpaperMetadataDto sse_decode_wallpaper_metadata_dto(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_title = sse_decode_opt_String(deserializer);
    var var_author = sse_decode_opt_String(deserializer);
    var var_description = sse_decode_opt_String(deserializer);
    var var_tags = sse_decode_list_String(deserializer);
    var var_durationSecs = sse_decode_opt_box_autoadd_f_64(deserializer);
    var var_resolutionWidth = sse_decode_opt_box_autoadd_u_32(deserializer);
    var var_resolutionHeight = sse_decode_opt_box_autoadd_u_32(deserializer);
    var var_fileSize = sse_decode_opt_box_autoadd_u_64(deserializer);
    var var_workshopId = sse_decode_opt_box_autoadd_u_64(deserializer);
    return WallpaperMetadataDto(
      title: var_title,
      author: var_author,
      description: var_description,
      tags: var_tags,
      durationSecs: var_durationSecs,
      resolutionWidth: var_resolutionWidth,
      resolutionHeight: var_resolutionHeight,
      fileSize: var_fileSize,
      workshopId: var_workshopId,
    );
  }

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWayvidService(
    WayvidService self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as WayvidServiceImpl).frbInternalSseEncode(move: true),
      serializer,
    );
  }

  @protected
  void
  sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWayvidService(
    WayvidService self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as WayvidServiceImpl).frbInternalSseEncode(move: false),
      serializer,
    );
  }

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWayvidService(
    WayvidService self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as WayvidServiceImpl).frbInternalSseEncode(move: null),
      serializer,
    );
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }

  @protected
  void sse_encode_box_autoadd_engine_config_dto(
    EngineConfigDto self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_engine_config_dto(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_f_64(double self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_f_64(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_u_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_32(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_u_64(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_64(self, serializer);
  }

  @protected
  void sse_encode_bridge_error(BridgeError self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.code, serializer);
    sse_encode_String(self.message, serializer);
  }

  @protected
  void sse_encode_engine_config_dto(
    EngineConfigDto self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_f_64(self.volume, serializer);
    sse_encode_opt_box_autoadd_u_32(self.fpsLimit, serializer);
    sse_encode_bool(self.loopPlayback, serializer);
    sse_encode_String(self.layout, serializer);
    sse_encode_String(self.hwdec, serializer);
    sse_encode_bool(self.mute, serializer);
    sse_encode_f_64(self.startTime, serializer);
    sse_encode_f_64(self.playbackRate, serializer);
    sse_encode_String(self.hdrMode, serializer);
    sse_encode_String(self.toneMappingAlgorithm, serializer);
    sse_encode_f_64(self.toneMappingParam, serializer);
    sse_encode_String(self.toneMappingMode, serializer);
    sse_encode_bool(self.toneMappingComputePeak, serializer);
    sse_encode_bool(self.autoPlay, serializer);
    sse_encode_bool(self.pauseOnBattery, serializer);
  }

  @protected
  void sse_encode_f_64(double self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putFloat64(self);
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_String(item, serializer);
    }
  }

  @protected
  void sse_encode_list_monitor_dto(
    List<MonitorDto> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_monitor_dto(item, serializer);
    }
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_list_service_event(
    List<ServiceEvent> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_service_event(item, serializer);
    }
  }

  @protected
  void sse_encode_list_wallpaper_dto(
    List<WallpaperDto> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_wallpaper_dto(item, serializer);
    }
  }

  @protected
  void sse_encode_monitor_dto(MonitorDto self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.name, serializer);
    sse_encode_u_32(self.width, serializer);
    sse_encode_u_32(self.height, serializer);
    sse_encode_i_32(self.x, serializer);
    sse_encode_i_32(self.y, serializer);
    sse_encode_f_64(self.scale, serializer);
    sse_encode_bool(self.primary, serializer);
    sse_encode_opt_String(self.currentWallpaper, serializer);
  }

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_String(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_f_64(double? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_f_64(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_u_32(int? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_u_32(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_u_64(BigInt? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_u_64(self, serializer);
    }
  }

  @protected
  void sse_encode_preview_dto(PreviewDto self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_opt_String(self.imagePath, serializer);
    sse_encode_list_prim_u_8_strict(self.bytes, serializer);
  }

  @protected
  void sse_encode_service_event(ServiceEvent self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    switch (self) {
      case ServiceEvent_EngineStarted():
        sse_encode_i_32(0, serializer);
      case ServiceEvent_EngineStopped():
        sse_encode_i_32(1, serializer);
      case ServiceEvent_WallpaperApplied(
        output: final output,
        path: final path,
      ):
        sse_encode_i_32(2, serializer);
        sse_encode_String(output, serializer);
        sse_encode_String(path, serializer);
      case ServiceEvent_WallpaperCleared(output: final output):
        sse_encode_i_32(3, serializer);
        sse_encode_String(output, serializer);
      case ServiceEvent_OutputsChanged(outputs: final outputs):
        sse_encode_i_32(4, serializer);
        sse_encode_list_monitor_dto(outputs, serializer);
      case ServiceEvent_Error(code: final code, message: final message):
        sse_encode_i_32(5, serializer);
        sse_encode_String(code, serializer);
        sse_encode_String(message, serializer);
    }
  }

  @protected
  void sse_encode_service_info(ServiceInfo self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_bool(self.workshopAvailable, serializer);
    sse_encode_bool(self.engineRunning, serializer);
  }

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint32(self);
  }

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putBigUint64(self);
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_usize(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putBigUint64(self);
  }

  @protected
  void sse_encode_wallpaper_dto(WallpaperDto self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.id, serializer);
    sse_encode_String(self.name, serializer);
    sse_encode_String(self.sourcePath, serializer);
    sse_encode_opt_String(self.thumbnailPath, serializer);
    sse_encode_String(self.sourceType, serializer);
    sse_encode_String(self.wallpaperCategory, serializer);
    sse_encode_String(self.wallpaperType, serializer);
    sse_encode_wallpaper_metadata_dto(self.metadata, serializer);
    sse_encode_String(self.addedAt, serializer);
    sse_encode_opt_String(self.lastUsed, serializer);
  }

  @protected
  void sse_encode_wallpaper_metadata_dto(
    WallpaperMetadataDto self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_opt_String(self.title, serializer);
    sse_encode_opt_String(self.author, serializer);
    sse_encode_opt_String(self.description, serializer);
    sse_encode_list_String(self.tags, serializer);
    sse_encode_opt_box_autoadd_f_64(self.durationSecs, serializer);
    sse_encode_opt_box_autoadd_u_32(self.resolutionWidth, serializer);
    sse_encode_opt_box_autoadd_u_32(self.resolutionHeight, serializer);
    sse_encode_opt_box_autoadd_u_64(self.fileSize, serializer);
    sse_encode_opt_box_autoadd_u_64(self.workshopId, serializer);
  }
}

@sealed
class WayvidServiceImpl extends RustOpaque implements WayvidService {
  // Not to be used by end users
  WayvidServiceImpl.frbInternalDcoDecode(List<dynamic> wire)
    : super.frbInternalDcoDecode(wire, _kStaticData);

  // Not to be used by end users
  WayvidServiceImpl.frbInternalSseDecode(BigInt ptr, int externalSizeOnNative)
    : super.frbInternalSseDecode(ptr, externalSizeOnNative, _kStaticData);

  static final _kStaticData = RustArcStaticData(
    rustArcIncrementStrongCount:
        RustLib.instance.api.rust_arc_increment_strong_count_WayvidService,
    rustArcDecrementStrongCount:
        RustLib.instance.api.rust_arc_decrement_strong_count_WayvidService,
    rustArcDecrementStrongCountPtr:
        RustLib.instance.api.rust_arc_decrement_strong_count_WayvidServicePtr,
  );

  Future<void> applyWallpaper({required String path, String? output}) =>
      RustLib.instance.api.crateBridgeWayvidServiceApplyWallpaper(
        that: this,
        path: path,
        output: output,
      );

  Future<void> clearWallpaper({String? output}) => RustLib.instance.api
      .crateBridgeWayvidServiceClearWallpaper(that: this, output: output);

  Future<void> createEngine({required EngineConfigDto config}) => RustLib
      .instance
      .api
      .crateBridgeWayvidServiceCreateEngine(that: this, config: config);

  Future<ServiceInfo> initialize() =>
      RustLib.instance.api.crateBridgeWayvidServiceInitialize(that: this);

  Future<PreviewDto> loadPreview({
    required String wallpaperId,
    required String path,
    required String wallpaperType,
    required int width,
    required int height,
  }) => RustLib.instance.api.crateBridgeWayvidServiceLoadPreview(
    that: this,
    wallpaperId: wallpaperId,
    path: path,
    wallpaperType: wallpaperType,
    width: width,
    height: height,
  );

  Future<void> openUrl({required String url}) => RustLib.instance.api
      .crateBridgeWayvidServiceOpenUrl(that: this, url: url);

  Future<void> pause({String? output}) => RustLib.instance.api
      .crateBridgeWayvidServicePause(that: this, output: output);

  Future<List<ServiceEvent>> pollEvents() =>
      RustLib.instance.api.crateBridgeWayvidServicePollEvents(that: this);

  Future<List<MonitorDto>> refreshMonitors() =>
      RustLib.instance.api.crateBridgeWayvidServiceRefreshMonitors(that: this);

  Future<void> resume({String? output}) => RustLib.instance.api
      .crateBridgeWayvidServiceResume(that: this, output: output);

  Future<List<WallpaperDto>> scanFolder({required String path}) => RustLib
      .instance
      .api
      .crateBridgeWayvidServiceScanFolder(that: this, path: path);

  Future<List<WallpaperDto>> scanWorkshop() =>
      RustLib.instance.api.crateBridgeWayvidServiceScanWorkshop(that: this);

  Future<void> shutdown() =>
      RustLib.instance.api.crateBridgeWayvidServiceShutdown(that: this);

  Future<void> stopEngine() =>
      RustLib.instance.api.crateBridgeWayvidServiceStopEngine(that: this);

  Future<void> updateEngineConfig({required EngineConfigDto config}) => RustLib
      .instance
      .api
      .crateBridgeWayvidServiceUpdateEngineConfig(that: this, config: config);
}
