// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'bridge.dart';

import 'dart:async';
import 'dart:convert';

import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Main entrypoint of the Rust API
class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
  @internal
  static final instance = RustLib._();

  RustLib._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    RustLibApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({required RustLibApi api}) {
    instance.initMockImpl(api: api);
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor =>
      RustLibApiImpl.new;

  @override
  WireConstructor<RustLibWire> get wireConstructor =>
      RustLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {}

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.12.0';

  @override
  int get rustContentHash => -1181887649;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
        stem: 'wayvid_gui',
        ioDirectory: 'rust/target/release/',
        webPrefix: 'pkg/',
        wasmBindgenName: 'wasm_bindgen',
      );
}

abstract class RustLibApi extends BaseApi {
  Future<void> crateBridgeWayvidServiceApplyWallpaper({
    required WayvidService that,
    required String wallpaperId,
    String? output,
  });

  Future<void> crateBridgeWayvidServiceClearWallpaper({
    required WayvidService that,
    String? output,
  });

  Future<SettingsDto> crateBridgeWayvidServiceGetSettings({
    required WayvidService that,
  });

  Future<InitializationSnapshot> crateBridgeWayvidServiceInitialize({
    required WayvidService that,
  });

  Future<List<WallpaperDto>> crateBridgeWayvidServiceLoadLibrary({
    required WayvidService that,
  });

  Future<Uint8List> crateBridgeWayvidServiceLoadThumbnail({
    required WayvidService that,
    required String wallpaperId,
    required String path,
    required int width,
    required int height,
  });

  Future<WayvidService> crateBridgeWayvidServiceNew({
    required List<String> args,
  });

  Future<void> crateBridgeWayvidServiceOpenUrl({
    required WayvidService that,
    required String url,
  });

  Future<void> crateBridgeWayvidServicePause({
    required WayvidService that,
    String? output,
  });

  Future<List<ServiceEvent>> crateBridgeWayvidServicePollEvents({
    required WayvidService that,
  });

  Future<List<MonitorDto>> crateBridgeWayvidServiceRefreshMonitors({
    required WayvidService that,
  });

  Future<void> crateBridgeWayvidServiceResume({
    required WayvidService that,
    String? output,
  });

  Future<List<WallpaperDto>> crateBridgeWayvidServiceScanFolder({
    required WayvidService that,
    required String path,
  });

  Future<List<WallpaperDto>> crateBridgeWayvidServiceScanWorkshop({
    required WayvidService that,
  });

  Future<void> crateBridgeWayvidServiceShutdown({required WayvidService that});

  Future<void> crateBridgeWayvidServiceStartEngine({
    required WayvidService that,
  });

  Future<void> crateBridgeWayvidServiceStopEngine({
    required WayvidService that,
  });

  Future<SettingsDto> crateBridgeWayvidServiceUpdateSettings({
    required WayvidService that,
    required SettingsPatch patch,
  });

  Future<SettingsPatch> crateBridgeSettingsPatchDefault();

  RustArcIncrementStrongCountFnType
  get rust_arc_increment_strong_count_WayvidService;

  RustArcDecrementStrongCountFnType
  get rust_arc_decrement_strong_count_WayvidService;

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_WayvidServicePtr;
}

class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
  RustLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  Future<void> crateBridgeWayvidServiceApplyWallpaper({
    required WayvidService that,
    required String wallpaperId,
    String? output,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWayvidService(
            that,
            serializer,
          );
          sse_encode_String(wallpaperId, serializer);
          sse_encode_opt_String(output, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 1,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_bridge_error,
        ),
        constMeta: kCrateBridgeWayvidServiceApplyWallpaperConstMeta,
        argValues: [that, wallpaperId, output],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateBridgeWayvidServiceApplyWallpaperConstMeta =>
      const TaskConstMeta(
        debugName: "WayvidService_apply_wallpaper",
        argNames: ["that", "wallpaperId", "output"],
      );

  @override
  Future<void> crateBridgeWayvidServiceClearWallpaper({
    required WayvidService that,
    String? output,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWayvidService(
            that,
            serializer,
          );
          sse_encode_opt_String(output, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 2,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_bridge_error,
        ),
        constMeta: kCrateBridgeWayvidServiceClearWallpaperConstMeta,
        argValues: [that, output],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateBridgeWayvidServiceClearWallpaperConstMeta =>
      const TaskConstMeta(
        debugName: "WayvidService_clear_wallpaper",
        argNames: ["that", "output"],
      );

  @override
  Future<SettingsDto> crateBridgeWayvidServiceGetSettings({
    required WayvidService that,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWayvidService(
            that,
            serializer,
          );
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 3,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_settings_dto,
          decodeErrorData: sse_decode_bridge_error,
        ),
        constMeta: kCrateBridgeWayvidServiceGetSettingsConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateBridgeWayvidServiceGetSettingsConstMeta =>
      const TaskConstMeta(
        debugName: "WayvidService_get_settings",
        argNames: ["that"],
      );

  @override
  Future<InitializationSnapshot> crateBridgeWayvidServiceInitialize({
    required WayvidService that,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWayvidService(
            that,
            serializer,
          );
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 4,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_initialization_snapshot,
          decodeErrorData: sse_decode_bridge_error,
        ),
        constMeta: kCrateBridgeWayvidServiceInitializeConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateBridgeWayvidServiceInitializeConstMeta =>
      const TaskConstMeta(
        debugName: "WayvidService_initialize",
        argNames: ["that"],
      );

  @override
  Future<List<WallpaperDto>> crateBridgeWayvidServiceLoadLibrary({
    required WayvidService that,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWayvidService(
            that,
            serializer,
          );
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 5,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_wallpaper_dto,
          decodeErrorData: sse_decode_bridge_error,
        ),
        constMeta: kCrateBridgeWayvidServiceLoadLibraryConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateBridgeWayvidServiceLoadLibraryConstMeta =>
      const TaskConstMeta(
        debugName: "WayvidService_load_library",
        argNames: ["that"],
      );

  @override
  Future<Uint8List> crateBridgeWayvidServiceLoadThumbnail({
    required WayvidService that,
    required String wallpaperId,
    required String path,
    required int width,
    required int height,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWayvidService(
            that,
            serializer,
          );
          sse_encode_String(wallpaperId, serializer);
          sse_encode_String(path, serializer);
          sse_encode_u_32(width, serializer);
          sse_encode_u_32(height, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 6,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_prim_u_8_strict,
          decodeErrorData: sse_decode_bridge_error,
        ),
        constMeta: kCrateBridgeWayvidServiceLoadThumbnailConstMeta,
        argValues: [that, wallpaperId, path, width, height],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateBridgeWayvidServiceLoadThumbnailConstMeta =>
      const TaskConstMeta(
        debugName: "WayvidService_load_thumbnail",
        argNames: ["that", "wallpaperId", "path", "width", "height"],
      );

  @override
  Future<WayvidService> crateBridgeWayvidServiceNew({
    required List<String> args,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_String(args, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 7,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData:
              sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWayvidService,
          decodeErrorData: sse_decode_bridge_error,
        ),
        constMeta: kCrateBridgeWayvidServiceNewConstMeta,
        argValues: [args],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateBridgeWayvidServiceNewConstMeta =>
      const TaskConstMeta(debugName: "WayvidService_new", argNames: ["args"]);

  @override
  Future<void> crateBridgeWayvidServiceOpenUrl({
    required WayvidService that,
    required String url,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWayvidService(
            that,
            serializer,
          );
          sse_encode_String(url, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 8,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_bridge_error,
        ),
        constMeta: kCrateBridgeWayvidServiceOpenUrlConstMeta,
        argValues: [that, url],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateBridgeWayvidServiceOpenUrlConstMeta =>
      const TaskConstMeta(
        debugName: "WayvidService_open_url",
        argNames: ["that", "url"],
      );

  @override
  Future<void> crateBridgeWayvidServicePause({
    required WayvidService that,
    String? output,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWayvidService(
            that,
            serializer,
          );
          sse_encode_opt_String(output, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 9,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_bridge_error,
        ),
        constMeta: kCrateBridgeWayvidServicePauseConstMeta,
        argValues: [that, output],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateBridgeWayvidServicePauseConstMeta =>
      const TaskConstMeta(
        debugName: "WayvidService_pause",
        argNames: ["that", "output"],
      );

  @override
  Future<List<ServiceEvent>> crateBridgeWayvidServicePollEvents({
    required WayvidService that,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWayvidService(
            that,
            serializer,
          );
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 10,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_service_event,
          decodeErrorData: sse_decode_bridge_error,
        ),
        constMeta: kCrateBridgeWayvidServicePollEventsConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateBridgeWayvidServicePollEventsConstMeta =>
      const TaskConstMeta(
        debugName: "WayvidService_poll_events",
        argNames: ["that"],
      );

  @override
  Future<List<MonitorDto>> crateBridgeWayvidServiceRefreshMonitors({
    required WayvidService that,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWayvidService(
            that,
            serializer,
          );
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 11,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_monitor_dto,
          decodeErrorData: sse_decode_bridge_error,
        ),
        constMeta: kCrateBridgeWayvidServiceRefreshMonitorsConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateBridgeWayvidServiceRefreshMonitorsConstMeta =>
      const TaskConstMeta(
        debugName: "WayvidService_refresh_monitors",
        argNames: ["that"],
      );

  @override
  Future<void> crateBridgeWayvidServiceResume({
    required WayvidService that,
    String? output,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWayvidService(
            that,
            serializer,
          );
          sse_encode_opt_String(output, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 12,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_bridge_error,
        ),
        constMeta: kCrateBridgeWayvidServiceResumeConstMeta,
        argValues: [that, output],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateBridgeWayvidServiceResumeConstMeta =>
      const TaskConstMeta(
        debugName: "WayvidService_resume",
        argNames: ["that", "output"],
      );

  @override
  Future<List<WallpaperDto>> crateBridgeWayvidServiceScanFolder({
    required WayvidService that,
    required String path,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWayvidService(
            that,
            serializer,
          );
          sse_encode_String(path, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 13,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_wallpaper_dto,
          decodeErrorData: sse_decode_bridge_error,
        ),
        constMeta: kCrateBridgeWayvidServiceScanFolderConstMeta,
        argValues: [that, path],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateBridgeWayvidServiceScanFolderConstMeta =>
      const TaskConstMeta(
        debugName: "WayvidService_scan_folder",
        argNames: ["that", "path"],
      );

  @override
  Future<List<WallpaperDto>> crateBridgeWayvidServiceScanWorkshop({
    required WayvidService that,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWayvidService(
            that,
            serializer,
          );
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 14,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_wallpaper_dto,
          decodeErrorData: sse_decode_bridge_error,
        ),
        constMeta: kCrateBridgeWayvidServiceScanWorkshopConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateBridgeWayvidServiceScanWorkshopConstMeta =>
      const TaskConstMeta(
        debugName: "WayvidService_scan_workshop",
        argNames: ["that"],
      );

  @override
  Future<void> crateBridgeWayvidServiceShutdown({required WayvidService that}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWayvidService(
            that,
            serializer,
          );
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 15,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_bridge_error,
        ),
        constMeta: kCrateBridgeWayvidServiceShutdownConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateBridgeWayvidServiceShutdownConstMeta =>
      const TaskConstMeta(
        debugName: "WayvidService_shutdown",
        argNames: ["that"],
      );

  @override
  Future<void> crateBridgeWayvidServiceStartEngine({
    required WayvidService that,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWayvidService(
            that,
            serializer,
          );
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 16,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_bridge_error,
        ),
        constMeta: kCrateBridgeWayvidServiceStartEngineConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateBridgeWayvidServiceStartEngineConstMeta =>
      const TaskConstMeta(
        debugName: "WayvidService_start_engine",
        argNames: ["that"],
      );

  @override
  Future<void> crateBridgeWayvidServiceStopEngine({
    required WayvidService that,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWayvidService(
            that,
            serializer,
          );
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 17,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_bridge_error,
        ),
        constMeta: kCrateBridgeWayvidServiceStopEngineConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateBridgeWayvidServiceStopEngineConstMeta =>
      const TaskConstMeta(
        debugName: "WayvidService_stop_engine",
        argNames: ["that"],
      );

  @override
  Future<SettingsDto> crateBridgeWayvidServiceUpdateSettings({
    required WayvidService that,
    required SettingsPatch patch,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWayvidService(
            that,
            serializer,
          );
          sse_encode_box_autoadd_settings_patch(patch, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 18,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_settings_dto,
          decodeErrorData: sse_decode_bridge_error,
        ),
        constMeta: kCrateBridgeWayvidServiceUpdateSettingsConstMeta,
        argValues: [that, patch],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateBridgeWayvidServiceUpdateSettingsConstMeta =>
      const TaskConstMeta(
        debugName: "WayvidService_update_settings",
        argNames: ["that", "patch"],
      );

  @override
  Future<SettingsPatch> crateBridgeSettingsPatchDefault() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 19,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_settings_patch,
          decodeErrorData: null,
        ),
        constMeta: kCrateBridgeSettingsPatchDefaultConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateBridgeSettingsPatchDefaultConstMeta =>
      const TaskConstMeta(debugName: "settings_patch_default", argNames: []);

  RustArcIncrementStrongCountFnType
  get rust_arc_increment_strong_count_WayvidService => wire
      .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWayvidService;

  RustArcDecrementStrongCountFnType
  get rust_arc_decrement_strong_count_WayvidService => wire
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWayvidService;

  @protected
  WayvidService
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWayvidService(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return WayvidServiceImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  WayvidService
  dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWayvidService(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return WayvidServiceImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  WayvidService
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWayvidService(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return WayvidServiceImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  bool dco_decode_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as bool;
  }

  @protected
  bool dco_decode_box_autoadd_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as bool;
  }

  @protected
  double dco_decode_box_autoadd_f_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as double;
  }

  @protected
  double dco_decode_box_autoadd_f_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as double;
  }

  @protected
  FpsLimitPatch dco_decode_box_autoadd_fps_limit_patch(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_fps_limit_patch(raw);
  }

  @protected
  SettingsPatch dco_decode_box_autoadd_settings_patch(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_settings_patch(raw);
  }

  @protected
  int dco_decode_box_autoadd_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  BigInt dco_decode_box_autoadd_u_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_u_64(raw);
  }

  @protected
  BridgeError dco_decode_bridge_error(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return BridgeError(
      code: dco_decode_String(arr[0]),
      message: dco_decode_String(arr[1]),
    );
  }

  @protected
  double dco_decode_f_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as double;
  }

  @protected
  double dco_decode_f_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as double;
  }

  @protected
  FpsLimitPatch dco_decode_fps_limit_patch(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    switch (raw[0]) {
      case 0:
        return FpsLimitPatch_Unlimited();
      case 1:
        return FpsLimitPatch_Value(dco_decode_u_32(raw[1]));
      default:
        throw Exception("unreachable");
    }
  }

  @protected
  GuiSettingsDto dco_decode_gui_settings_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 9)
      throw Exception('unexpected arr length: expect 9 but see ${arr.length}');
    return GuiSettingsDto(
      windowWidth: dco_decode_u_32(arr[0]),
      windowHeight: dco_decode_u_32(arr[1]),
      minimizeToTray: dco_decode_bool(arr[2]),
      startMinimized: dco_decode_bool(arr[3]),
      theme: dco_decode_String(arr[4]),
      language: dco_decode_String(arr[5]),
      renderer: dco_decode_String(arr[6]),
      sidebarCollapsed: dco_decode_bool(arr[7]),
      detailPanelVisible: dco_decode_bool(arr[8]),
    );
  }

  @protected
  int dco_decode_i_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  InitializationSnapshot dco_decode_initialization_snapshot(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 5)
      throw Exception('unexpected arr length: expect 5 but see ${arr.length}');
    return InitializationSnapshot(
      settings: dco_decode_settings_dto(arr[0]),
      workshopAvailable: dco_decode_bool(arr[1]),
      engineRunning: dco_decode_bool(arr[2]),
      trayAvailable: dco_decode_bool(arr[3]),
      anotherInstance: dco_decode_bool(arr[4]),
    );
  }

  @protected
  List<String> dco_decode_list_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_String).toList();
  }

  @protected
  List<MonitorDto> dco_decode_list_monitor_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_monitor_dto).toList();
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  List<ServiceEvent> dco_decode_list_service_event(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_service_event).toList();
  }

  @protected
  List<WallpaperDto> dco_decode_list_wallpaper_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_wallpaper_dto).toList();
  }

  @protected
  MonitorDto dco_decode_monitor_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 8)
      throw Exception('unexpected arr length: expect 8 but see ${arr.length}');
    return MonitorDto(
      name: dco_decode_String(arr[0]),
      width: dco_decode_u_32(arr[1]),
      height: dco_decode_u_32(arr[2]),
      x: dco_decode_i_32(arr[3]),
      y: dco_decode_i_32(arr[4]),
      scale: dco_decode_f_64(arr[5]),
      primary: dco_decode_bool(arr[6]),
      currentWallpaper: dco_decode_opt_String(arr[7]),
    );
  }

  @protected
  String? dco_decode_opt_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_String(raw);
  }

  @protected
  bool? dco_decode_opt_box_autoadd_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_bool(raw);
  }

  @protected
  double? dco_decode_opt_box_autoadd_f_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_f_32(raw);
  }

  @protected
  double? dco_decode_opt_box_autoadd_f_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_f_64(raw);
  }

  @protected
  FpsLimitPatch? dco_decode_opt_box_autoadd_fps_limit_patch(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_fps_limit_patch(raw);
  }

  @protected
  int? dco_decode_opt_box_autoadd_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_u_32(raw);
  }

  @protected
  BigInt? dco_decode_opt_box_autoadd_u_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_u_64(raw);
  }

  @protected
  List<String>? dco_decode_opt_list_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_list_String(raw);
  }

  @protected
  PlaybackSettingsDto dco_decode_playback_settings_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 5)
      throw Exception('unexpected arr length: expect 5 but see ${arr.length}');
    return PlaybackSettingsDto(
      volume: dco_decode_f_32(arr[0]),
      fpsLimit: dco_decode_opt_box_autoadd_u_32(arr[1]),
      preferredMonitor: dco_decode_opt_String(arr[2]),
      loopMode: dco_decode_bool(arr[3]),
      shuffle: dco_decode_bool(arr[4]),
    );
  }

  @protected
  PowerSettingsDto dco_decode_power_settings_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return PowerSettingsDto(
      pauseOnBattery: dco_decode_bool(arr[0]),
      pauseOnFullscreen: dco_decode_bool(arr[1]),
      batteryFpsLimit: dco_decode_opt_box_autoadd_u_32(arr[2]),
    );
  }

  @protected
  ServiceEvent dco_decode_service_event(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    switch (raw[0]) {
      case 0:
        return ServiceEvent_EngineStarted();
      case 1:
        return ServiceEvent_EngineStopped();
      case 2:
        return ServiceEvent_WallpaperApplied(
          output: dco_decode_String(raw[1]),
          path: dco_decode_String(raw[2]),
        );
      case 3:
        return ServiceEvent_WallpaperCleared(output: dco_decode_String(raw[1]));
      case 4:
        return ServiceEvent_OutputsChanged(
          outputs: dco_decode_list_monitor_dto(raw[1]),
        );
      case 5:
        return ServiceEvent_ShowWindow();
      case 6:
        return ServiceEvent_TrayAction(action: dco_decode_String(raw[1]));
      case 7:
        return ServiceEvent_Error(
          code: dco_decode_String(raw[1]),
          message: dco_decode_String(raw[2]),
        );
      default:
        throw Exception("unreachable");
    }
  }

  @protected
  SettingsDto dco_decode_settings_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 6)
      throw Exception('unexpected arr length: expect 6 but see ${arr.length}');
    return SettingsDto(
      gui: dco_decode_gui_settings_dto(arr[0]),
      playback: dco_decode_playback_settings_dto(arr[1]),
      autostartEnabled: dco_decode_bool(arr[2]),
      restoreLastWallpaper: dco_decode_bool(arr[3]),
      power: dco_decode_power_settings_dto(arr[4]),
      libraryFolders: dco_decode_list_String(arr[5]),
    );
  }

  @protected
  SettingsPatch dco_decode_settings_patch(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 16)
      throw Exception('unexpected arr length: expect 16 but see ${arr.length}');
    return SettingsPatch(
      windowWidth: dco_decode_opt_box_autoadd_u_32(arr[0]),
      windowHeight: dco_decode_opt_box_autoadd_u_32(arr[1]),
      minimizeToTray: dco_decode_opt_box_autoadd_bool(arr[2]),
      startMinimized: dco_decode_opt_box_autoadd_bool(arr[3]),
      theme: dco_decode_opt_String(arr[4]),
      language: dco_decode_opt_String(arr[5]),
      renderer: dco_decode_opt_String(arr[6]),
      sidebarCollapsed: dco_decode_opt_box_autoadd_bool(arr[7]),
      detailPanelVisible: dco_decode_opt_box_autoadd_bool(arr[8]),
      volume: dco_decode_opt_box_autoadd_f_32(arr[9]),
      fpsLimit: dco_decode_opt_box_autoadd_fps_limit_patch(arr[10]),
      pauseOnBattery: dco_decode_opt_box_autoadd_bool(arr[11]),
      pauseOnFullscreen: dco_decode_opt_box_autoadd_bool(arr[12]),
      autostartEnabled: dco_decode_opt_box_autoadd_bool(arr[13]),
      restoreLastWallpaper: dco_decode_opt_box_autoadd_bool(arr[14]),
      libraryFolders: dco_decode_opt_list_String(arr[15]),
    );
  }

  @protected
  int dco_decode_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  BigInt dco_decode_u_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeU64(raw);
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  BigInt dco_decode_usize(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeU64(raw);
  }

  @protected
  WallpaperDto dco_decode_wallpaper_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 9)
      throw Exception('unexpected arr length: expect 9 but see ${arr.length}');
    return WallpaperDto(
      id: dco_decode_String(arr[0]),
      name: dco_decode_String(arr[1]),
      sourcePath: dco_decode_String(arr[2]),
      thumbnailPath: dco_decode_opt_String(arr[3]),
      sourceType: dco_decode_String(arr[4]),
      wallpaperType: dco_decode_String(arr[5]),
      metadata: dco_decode_wallpaper_metadata_dto(arr[6]),
      addedAt: dco_decode_String(arr[7]),
      lastUsed: dco_decode_opt_String(arr[8]),
    );
  }

  @protected
  WallpaperMetadataDto dco_decode_wallpaper_metadata_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 9)
      throw Exception('unexpected arr length: expect 9 but see ${arr.length}');
    return WallpaperMetadataDto(
      title: dco_decode_opt_String(arr[0]),
      author: dco_decode_opt_String(arr[1]),
      description: dco_decode_opt_String(arr[2]),
      tags: dco_decode_list_String(arr[3]),
      durationSecs: dco_decode_opt_box_autoadd_f_64(arr[4]),
      resolutionWidth: dco_decode_opt_box_autoadd_u_32(arr[5]),
      resolutionHeight: dco_decode_opt_box_autoadd_u_32(arr[6]),
      fileSize: dco_decode_opt_box_autoadd_u_64(arr[7]),
      workshopId: dco_decode_opt_box_autoadd_u_64(arr[8]),
    );
  }

  @protected
  WayvidService
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWayvidService(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return WayvidServiceImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  WayvidService
  sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWayvidService(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return WayvidServiceImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  WayvidService
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWayvidService(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return WayvidServiceImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  bool sse_decode_box_autoadd_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_bool(deserializer));
  }

  @protected
  double sse_decode_box_autoadd_f_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_f_32(deserializer));
  }

  @protected
  double sse_decode_box_autoadd_f_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_f_64(deserializer));
  }

  @protected
  FpsLimitPatch sse_decode_box_autoadd_fps_limit_patch(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_fps_limit_patch(deserializer));
  }

  @protected
  SettingsPatch sse_decode_box_autoadd_settings_patch(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_settings_patch(deserializer));
  }

  @protected
  int sse_decode_box_autoadd_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_u_32(deserializer));
  }

  @protected
  BigInt sse_decode_box_autoadd_u_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_u_64(deserializer));
  }

  @protected
  BridgeError sse_decode_bridge_error(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_code = sse_decode_String(deserializer);
    var var_message = sse_decode_String(deserializer);
    return BridgeError(code: var_code, message: var_message);
  }

  @protected
  double sse_decode_f_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getFloat32();
  }

  @protected
  double sse_decode_f_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getFloat64();
  }

  @protected
  FpsLimitPatch sse_decode_fps_limit_patch(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var tag_ = sse_decode_i_32(deserializer);
    switch (tag_) {
      case 0:
        return FpsLimitPatch_Unlimited();
      case 1:
        var var_field0 = sse_decode_u_32(deserializer);
        return FpsLimitPatch_Value(var_field0);
      default:
        throw UnimplementedError('');
    }
  }

  @protected
  GuiSettingsDto sse_decode_gui_settings_dto(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_windowWidth = sse_decode_u_32(deserializer);
    var var_windowHeight = sse_decode_u_32(deserializer);
    var var_minimizeToTray = sse_decode_bool(deserializer);
    var var_startMinimized = sse_decode_bool(deserializer);
    var var_theme = sse_decode_String(deserializer);
    var var_language = sse_decode_String(deserializer);
    var var_renderer = sse_decode_String(deserializer);
    var var_sidebarCollapsed = sse_decode_bool(deserializer);
    var var_detailPanelVisible = sse_decode_bool(deserializer);
    return GuiSettingsDto(
      windowWidth: var_windowWidth,
      windowHeight: var_windowHeight,
      minimizeToTray: var_minimizeToTray,
      startMinimized: var_startMinimized,
      theme: var_theme,
      language: var_language,
      renderer: var_renderer,
      sidebarCollapsed: var_sidebarCollapsed,
      detailPanelVisible: var_detailPanelVisible,
    );
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  InitializationSnapshot sse_decode_initialization_snapshot(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_settings = sse_decode_settings_dto(deserializer);
    var var_workshopAvailable = sse_decode_bool(deserializer);
    var var_engineRunning = sse_decode_bool(deserializer);
    var var_trayAvailable = sse_decode_bool(deserializer);
    var var_anotherInstance = sse_decode_bool(deserializer);
    return InitializationSnapshot(
      settings: var_settings,
      workshopAvailable: var_workshopAvailable,
      engineRunning: var_engineRunning,
      trayAvailable: var_trayAvailable,
      anotherInstance: var_anotherInstance,
    );
  }

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <String>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_String(deserializer));
    }
    return ans_;
  }

  @protected
  List<MonitorDto> sse_decode_list_monitor_dto(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <MonitorDto>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_monitor_dto(deserializer));
    }
    return ans_;
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  List<ServiceEvent> sse_decode_list_service_event(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <ServiceEvent>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_service_event(deserializer));
    }
    return ans_;
  }

  @protected
  List<WallpaperDto> sse_decode_list_wallpaper_dto(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <WallpaperDto>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_wallpaper_dto(deserializer));
    }
    return ans_;
  }

  @protected
  MonitorDto sse_decode_monitor_dto(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_name = sse_decode_String(deserializer);
    var var_width = sse_decode_u_32(deserializer);
    var var_height = sse_decode_u_32(deserializer);
    var var_x = sse_decode_i_32(deserializer);
    var var_y = sse_decode_i_32(deserializer);
    var var_scale = sse_decode_f_64(deserializer);
    var var_primary = sse_decode_bool(deserializer);
    var var_currentWallpaper = sse_decode_opt_String(deserializer);
    return MonitorDto(
      name: var_name,
      width: var_width,
      height: var_height,
      x: var_x,
      y: var_y,
      scale: var_scale,
      primary: var_primary,
      currentWallpaper: var_currentWallpaper,
    );
  }

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_String(deserializer));
    } else {
      return null;
    }
  }

  @protected
  bool? sse_decode_opt_box_autoadd_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_bool(deserializer));
    } else {
      return null;
    }
  }

  @protected
  double? sse_decode_opt_box_autoadd_f_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_f_32(deserializer));
    } else {
      return null;
    }
  }

  @protected
  double? sse_decode_opt_box_autoadd_f_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_f_64(deserializer));
    } else {
      return null;
    }
  }

  @protected
  FpsLimitPatch? sse_decode_opt_box_autoadd_fps_limit_patch(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_fps_limit_patch(deserializer));
    } else {
      return null;
    }
  }

  @protected
  int? sse_decode_opt_box_autoadd_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_u_32(deserializer));
    } else {
      return null;
    }
  }

  @protected
  BigInt? sse_decode_opt_box_autoadd_u_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_u_64(deserializer));
    } else {
      return null;
    }
  }

  @protected
  List<String>? sse_decode_opt_list_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_list_String(deserializer));
    } else {
      return null;
    }
  }

  @protected
  PlaybackSettingsDto sse_decode_playback_settings_dto(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_volume = sse_decode_f_32(deserializer);
    var var_fpsLimit = sse_decode_opt_box_autoadd_u_32(deserializer);
    var var_preferredMonitor = sse_decode_opt_String(deserializer);
    var var_loopMode = sse_decode_bool(deserializer);
    var var_shuffle = sse_decode_bool(deserializer);
    return PlaybackSettingsDto(
      volume: var_volume,
      fpsLimit: var_fpsLimit,
      preferredMonitor: var_preferredMonitor,
      loopMode: var_loopMode,
      shuffle: var_shuffle,
    );
  }

  @protected
  PowerSettingsDto sse_decode_power_settings_dto(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_pauseOnBattery = sse_decode_bool(deserializer);
    var var_pauseOnFullscreen = sse_decode_bool(deserializer);
    var var_batteryFpsLimit = sse_decode_opt_box_autoadd_u_32(deserializer);
    return PowerSettingsDto(
      pauseOnBattery: var_pauseOnBattery,
      pauseOnFullscreen: var_pauseOnFullscreen,
      batteryFpsLimit: var_batteryFpsLimit,
    );
  }

  @protected
  ServiceEvent sse_decode_service_event(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var tag_ = sse_decode_i_32(deserializer);
    switch (tag_) {
      case 0:
        return ServiceEvent_EngineStarted();
      case 1:
        return ServiceEvent_EngineStopped();
      case 2:
        var var_output = sse_decode_String(deserializer);
        var var_path = sse_decode_String(deserializer);
        return ServiceEvent_WallpaperApplied(
          output: var_output,
          path: var_path,
        );
      case 3:
        var var_output = sse_decode_String(deserializer);
        return ServiceEvent_WallpaperCleared(output: var_output);
      case 4:
        var var_outputs = sse_decode_list_monitor_dto(deserializer);
        return ServiceEvent_OutputsChanged(outputs: var_outputs);
      case 5:
        return ServiceEvent_ShowWindow();
      case 6:
        var var_action = sse_decode_String(deserializer);
        return ServiceEvent_TrayAction(action: var_action);
      case 7:
        var var_code = sse_decode_String(deserializer);
        var var_message = sse_decode_String(deserializer);
        return ServiceEvent_Error(code: var_code, message: var_message);
      default:
        throw UnimplementedError('');
    }
  }

  @protected
  SettingsDto sse_decode_settings_dto(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_gui = sse_decode_gui_settings_dto(deserializer);
    var var_playback = sse_decode_playback_settings_dto(deserializer);
    var var_autostartEnabled = sse_decode_bool(deserializer);
    var var_restoreLastWallpaper = sse_decode_bool(deserializer);
    var var_power = sse_decode_power_settings_dto(deserializer);
    var var_libraryFolders = sse_decode_list_String(deserializer);
    return SettingsDto(
      gui: var_gui,
      playback: var_playback,
      autostartEnabled: var_autostartEnabled,
      restoreLastWallpaper: var_restoreLastWallpaper,
      power: var_power,
      libraryFolders: var_libraryFolders,
    );
  }

  @protected
  SettingsPatch sse_decode_settings_patch(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_windowWidth = sse_decode_opt_box_autoadd_u_32(deserializer);
    var var_windowHeight = sse_decode_opt_box_autoadd_u_32(deserializer);
    var var_minimizeToTray = sse_decode_opt_box_autoadd_bool(deserializer);
    var var_startMinimized = sse_decode_opt_box_autoadd_bool(deserializer);
    var var_theme = sse_decode_opt_String(deserializer);
    var var_language = sse_decode_opt_String(deserializer);
    var var_renderer = sse_decode_opt_String(deserializer);
    var var_sidebarCollapsed = sse_decode_opt_box_autoadd_bool(deserializer);
    var var_detailPanelVisible = sse_decode_opt_box_autoadd_bool(deserializer);
    var var_volume = sse_decode_opt_box_autoadd_f_32(deserializer);
    var var_fpsLimit = sse_decode_opt_box_autoadd_fps_limit_patch(deserializer);
    var var_pauseOnBattery = sse_decode_opt_box_autoadd_bool(deserializer);
    var var_pauseOnFullscreen = sse_decode_opt_box_autoadd_bool(deserializer);
    var var_autostartEnabled = sse_decode_opt_box_autoadd_bool(deserializer);
    var var_restoreLastWallpaper = sse_decode_opt_box_autoadd_bool(
      deserializer,
    );
    var var_libraryFolders = sse_decode_opt_list_String(deserializer);
    return SettingsPatch(
      windowWidth: var_windowWidth,
      windowHeight: var_windowHeight,
      minimizeToTray: var_minimizeToTray,
      startMinimized: var_startMinimized,
      theme: var_theme,
      language: var_language,
      renderer: var_renderer,
      sidebarCollapsed: var_sidebarCollapsed,
      detailPanelVisible: var_detailPanelVisible,
      volume: var_volume,
      fpsLimit: var_fpsLimit,
      pauseOnBattery: var_pauseOnBattery,
      pauseOnFullscreen: var_pauseOnFullscreen,
      autostartEnabled: var_autostartEnabled,
      restoreLastWallpaper: var_restoreLastWallpaper,
      libraryFolders: var_libraryFolders,
    );
  }

  @protected
  int sse_decode_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint32();
  }

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getBigUint64();
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  BigInt sse_decode_usize(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getBigUint64();
  }

  @protected
  WallpaperDto sse_decode_wallpaper_dto(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_id = sse_decode_String(deserializer);
    var var_name = sse_decode_String(deserializer);
    var var_sourcePath = sse_decode_String(deserializer);
    var var_thumbnailPath = sse_decode_opt_String(deserializer);
    var var_sourceType = sse_decode_String(deserializer);
    var var_wallpaperType = sse_decode_String(deserializer);
    var var_metadata = sse_decode_wallpaper_metadata_dto(deserializer);
    var var_addedAt = sse_decode_String(deserializer);
    var var_lastUsed = sse_decode_opt_String(deserializer);
    return WallpaperDto(
      id: var_id,
      name: var_name,
      sourcePath: var_sourcePath,
      thumbnailPath: var_thumbnailPath,
      sourceType: var_sourceType,
      wallpaperType: var_wallpaperType,
      metadata: var_metadata,
      addedAt: var_addedAt,
      lastUsed: var_lastUsed,
    );
  }

  @protected
  WallpaperMetadataDto sse_decode_wallpaper_metadata_dto(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_title = sse_decode_opt_String(deserializer);
    var var_author = sse_decode_opt_String(deserializer);
    var var_description = sse_decode_opt_String(deserializer);
    var var_tags = sse_decode_list_String(deserializer);
    var var_durationSecs = sse_decode_opt_box_autoadd_f_64(deserializer);
    var var_resolutionWidth = sse_decode_opt_box_autoadd_u_32(deserializer);
    var var_resolutionHeight = sse_decode_opt_box_autoadd_u_32(deserializer);
    var var_fileSize = sse_decode_opt_box_autoadd_u_64(deserializer);
    var var_workshopId = sse_decode_opt_box_autoadd_u_64(deserializer);
    return WallpaperMetadataDto(
      title: var_title,
      author: var_author,
      description: var_description,
      tags: var_tags,
      durationSecs: var_durationSecs,
      resolutionWidth: var_resolutionWidth,
      resolutionHeight: var_resolutionHeight,
      fileSize: var_fileSize,
      workshopId: var_workshopId,
    );
  }

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWayvidService(
    WayvidService self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as WayvidServiceImpl).frbInternalSseEncode(move: true),
      serializer,
    );
  }

  @protected
  void
  sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWayvidService(
    WayvidService self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as WayvidServiceImpl).frbInternalSseEncode(move: false),
      serializer,
    );
  }

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWayvidService(
    WayvidService self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as WayvidServiceImpl).frbInternalSseEncode(move: null),
      serializer,
    );
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }

  @protected
  void sse_encode_box_autoadd_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_bool(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_f_32(double self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_f_32(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_f_64(double self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_f_64(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_fps_limit_patch(
    FpsLimitPatch self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_fps_limit_patch(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_settings_patch(
    SettingsPatch self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_settings_patch(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_u_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_32(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_u_64(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_64(self, serializer);
  }

  @protected
  void sse_encode_bridge_error(BridgeError self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.code, serializer);
    sse_encode_String(self.message, serializer);
  }

  @protected
  void sse_encode_f_32(double self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putFloat32(self);
  }

  @protected
  void sse_encode_f_64(double self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putFloat64(self);
  }

  @protected
  void sse_encode_fps_limit_patch(
    FpsLimitPatch self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    switch (self) {
      case FpsLimitPatch_Unlimited():
        sse_encode_i_32(0, serializer);
      case FpsLimitPatch_Value(field0: final field0):
        sse_encode_i_32(1, serializer);
        sse_encode_u_32(field0, serializer);
    }
  }

  @protected
  void sse_encode_gui_settings_dto(
    GuiSettingsDto self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_32(self.windowWidth, serializer);
    sse_encode_u_32(self.windowHeight, serializer);
    sse_encode_bool(self.minimizeToTray, serializer);
    sse_encode_bool(self.startMinimized, serializer);
    sse_encode_String(self.theme, serializer);
    sse_encode_String(self.language, serializer);
    sse_encode_String(self.renderer, serializer);
    sse_encode_bool(self.sidebarCollapsed, serializer);
    sse_encode_bool(self.detailPanelVisible, serializer);
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }

  @protected
  void sse_encode_initialization_snapshot(
    InitializationSnapshot self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_settings_dto(self.settings, serializer);
    sse_encode_bool(self.workshopAvailable, serializer);
    sse_encode_bool(self.engineRunning, serializer);
    sse_encode_bool(self.trayAvailable, serializer);
    sse_encode_bool(self.anotherInstance, serializer);
  }

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_String(item, serializer);
    }
  }

  @protected
  void sse_encode_list_monitor_dto(
    List<MonitorDto> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_monitor_dto(item, serializer);
    }
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_list_service_event(
    List<ServiceEvent> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_service_event(item, serializer);
    }
  }

  @protected
  void sse_encode_list_wallpaper_dto(
    List<WallpaperDto> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_wallpaper_dto(item, serializer);
    }
  }

  @protected
  void sse_encode_monitor_dto(MonitorDto self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.name, serializer);
    sse_encode_u_32(self.width, serializer);
    sse_encode_u_32(self.height, serializer);
    sse_encode_i_32(self.x, serializer);
    sse_encode_i_32(self.y, serializer);
    sse_encode_f_64(self.scale, serializer);
    sse_encode_bool(self.primary, serializer);
    sse_encode_opt_String(self.currentWallpaper, serializer);
  }

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_String(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_bool(bool? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_bool(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_f_32(double? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_f_32(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_f_64(double? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_f_64(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_fps_limit_patch(
    FpsLimitPatch? self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_fps_limit_patch(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_u_32(int? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_u_32(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_u_64(BigInt? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_u_64(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_list_String(
    List<String>? self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_list_String(self, serializer);
    }
  }

  @protected
  void sse_encode_playback_settings_dto(
    PlaybackSettingsDto self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_f_32(self.volume, serializer);
    sse_encode_opt_box_autoadd_u_32(self.fpsLimit, serializer);
    sse_encode_opt_String(self.preferredMonitor, serializer);
    sse_encode_bool(self.loopMode, serializer);
    sse_encode_bool(self.shuffle, serializer);
  }

  @protected
  void sse_encode_power_settings_dto(
    PowerSettingsDto self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_bool(self.pauseOnBattery, serializer);
    sse_encode_bool(self.pauseOnFullscreen, serializer);
    sse_encode_opt_box_autoadd_u_32(self.batteryFpsLimit, serializer);
  }

  @protected
  void sse_encode_service_event(ServiceEvent self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    switch (self) {
      case ServiceEvent_EngineStarted():
        sse_encode_i_32(0, serializer);
      case ServiceEvent_EngineStopped():
        sse_encode_i_32(1, serializer);
      case ServiceEvent_WallpaperApplied(
        output: final output,
        path: final path,
      ):
        sse_encode_i_32(2, serializer);
        sse_encode_String(output, serializer);
        sse_encode_String(path, serializer);
      case ServiceEvent_WallpaperCleared(output: final output):
        sse_encode_i_32(3, serializer);
        sse_encode_String(output, serializer);
      case ServiceEvent_OutputsChanged(outputs: final outputs):
        sse_encode_i_32(4, serializer);
        sse_encode_list_monitor_dto(outputs, serializer);
      case ServiceEvent_ShowWindow():
        sse_encode_i_32(5, serializer);
      case ServiceEvent_TrayAction(action: final action):
        sse_encode_i_32(6, serializer);
        sse_encode_String(action, serializer);
      case ServiceEvent_Error(code: final code, message: final message):
        sse_encode_i_32(7, serializer);
        sse_encode_String(code, serializer);
        sse_encode_String(message, serializer);
    }
  }

  @protected
  void sse_encode_settings_dto(SettingsDto self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_gui_settings_dto(self.gui, serializer);
    sse_encode_playback_settings_dto(self.playback, serializer);
    sse_encode_bool(self.autostartEnabled, serializer);
    sse_encode_bool(self.restoreLastWallpaper, serializer);
    sse_encode_power_settings_dto(self.power, serializer);
    sse_encode_list_String(self.libraryFolders, serializer);
  }

  @protected
  void sse_encode_settings_patch(SettingsPatch self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_opt_box_autoadd_u_32(self.windowWidth, serializer);
    sse_encode_opt_box_autoadd_u_32(self.windowHeight, serializer);
    sse_encode_opt_box_autoadd_bool(self.minimizeToTray, serializer);
    sse_encode_opt_box_autoadd_bool(self.startMinimized, serializer);
    sse_encode_opt_String(self.theme, serializer);
    sse_encode_opt_String(self.language, serializer);
    sse_encode_opt_String(self.renderer, serializer);
    sse_encode_opt_box_autoadd_bool(self.sidebarCollapsed, serializer);
    sse_encode_opt_box_autoadd_bool(self.detailPanelVisible, serializer);
    sse_encode_opt_box_autoadd_f_32(self.volume, serializer);
    sse_encode_opt_box_autoadd_fps_limit_patch(self.fpsLimit, serializer);
    sse_encode_opt_box_autoadd_bool(self.pauseOnBattery, serializer);
    sse_encode_opt_box_autoadd_bool(self.pauseOnFullscreen, serializer);
    sse_encode_opt_box_autoadd_bool(self.autostartEnabled, serializer);
    sse_encode_opt_box_autoadd_bool(self.restoreLastWallpaper, serializer);
    sse_encode_opt_list_String(self.libraryFolders, serializer);
  }

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint32(self);
  }

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putBigUint64(self);
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_usize(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putBigUint64(self);
  }

  @protected
  void sse_encode_wallpaper_dto(WallpaperDto self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.id, serializer);
    sse_encode_String(self.name, serializer);
    sse_encode_String(self.sourcePath, serializer);
    sse_encode_opt_String(self.thumbnailPath, serializer);
    sse_encode_String(self.sourceType, serializer);
    sse_encode_String(self.wallpaperType, serializer);
    sse_encode_wallpaper_metadata_dto(self.metadata, serializer);
    sse_encode_String(self.addedAt, serializer);
    sse_encode_opt_String(self.lastUsed, serializer);
  }

  @protected
  void sse_encode_wallpaper_metadata_dto(
    WallpaperMetadataDto self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_opt_String(self.title, serializer);
    sse_encode_opt_String(self.author, serializer);
    sse_encode_opt_String(self.description, serializer);
    sse_encode_list_String(self.tags, serializer);
    sse_encode_opt_box_autoadd_f_64(self.durationSecs, serializer);
    sse_encode_opt_box_autoadd_u_32(self.resolutionWidth, serializer);
    sse_encode_opt_box_autoadd_u_32(self.resolutionHeight, serializer);
    sse_encode_opt_box_autoadd_u_64(self.fileSize, serializer);
    sse_encode_opt_box_autoadd_u_64(self.workshopId, serializer);
  }
}

@sealed
class WayvidServiceImpl extends RustOpaque implements WayvidService {
  // Not to be used by end users
  WayvidServiceImpl.frbInternalDcoDecode(List<dynamic> wire)
    : super.frbInternalDcoDecode(wire, _kStaticData);

  // Not to be used by end users
  WayvidServiceImpl.frbInternalSseDecode(BigInt ptr, int externalSizeOnNative)
    : super.frbInternalSseDecode(ptr, externalSizeOnNative, _kStaticData);

  static final _kStaticData = RustArcStaticData(
    rustArcIncrementStrongCount:
        RustLib.instance.api.rust_arc_increment_strong_count_WayvidService,
    rustArcDecrementStrongCount:
        RustLib.instance.api.rust_arc_decrement_strong_count_WayvidService,
    rustArcDecrementStrongCountPtr:
        RustLib.instance.api.rust_arc_decrement_strong_count_WayvidServicePtr,
  );

  Future<void> applyWallpaper({required String wallpaperId, String? output}) =>
      RustLib.instance.api.crateBridgeWayvidServiceApplyWallpaper(
        that: this,
        wallpaperId: wallpaperId,
        output: output,
      );

  Future<void> clearWallpaper({String? output}) => RustLib.instance.api
      .crateBridgeWayvidServiceClearWallpaper(that: this, output: output);

  Future<SettingsDto> getSettings() =>
      RustLib.instance.api.crateBridgeWayvidServiceGetSettings(that: this);

  Future<InitializationSnapshot> initialize() =>
      RustLib.instance.api.crateBridgeWayvidServiceInitialize(that: this);

  Future<List<WallpaperDto>> loadLibrary() =>
      RustLib.instance.api.crateBridgeWayvidServiceLoadLibrary(that: this);

  Future<Uint8List> loadThumbnail({
    required String wallpaperId,
    required String path,
    required int width,
    required int height,
  }) => RustLib.instance.api.crateBridgeWayvidServiceLoadThumbnail(
    that: this,
    wallpaperId: wallpaperId,
    path: path,
    width: width,
    height: height,
  );

  Future<void> openUrl({required String url}) => RustLib.instance.api
      .crateBridgeWayvidServiceOpenUrl(that: this, url: url);

  Future<void> pause({String? output}) => RustLib.instance.api
      .crateBridgeWayvidServicePause(that: this, output: output);

  Future<List<ServiceEvent>> pollEvents() =>
      RustLib.instance.api.crateBridgeWayvidServicePollEvents(that: this);

  Future<List<MonitorDto>> refreshMonitors() =>
      RustLib.instance.api.crateBridgeWayvidServiceRefreshMonitors(that: this);

  Future<void> resume({String? output}) => RustLib.instance.api
      .crateBridgeWayvidServiceResume(that: this, output: output);

  Future<List<WallpaperDto>> scanFolder({required String path}) => RustLib
      .instance
      .api
      .crateBridgeWayvidServiceScanFolder(that: this, path: path);

  Future<List<WallpaperDto>> scanWorkshop() =>
      RustLib.instance.api.crateBridgeWayvidServiceScanWorkshop(that: this);

  Future<void> shutdown() =>
      RustLib.instance.api.crateBridgeWayvidServiceShutdown(that: this);

  Future<void> startEngine() =>
      RustLib.instance.api.crateBridgeWayvidServiceStartEngine(that: this);

  Future<void> stopEngine() =>
      RustLib.instance.api.crateBridgeWayvidServiceStopEngine(that: this);

  Future<SettingsDto> updateSettings({required SettingsPatch patch}) => RustLib
      .instance
      .api
      .crateBridgeWayvidServiceUpdateSettings(that: this, patch: patch);
}
